### ISSUE TITLE
Add content on Cognitive Task Analysis (or the 4C/ID model) to Lesson Design

### ISSUE THREAD

**Issue by tedyoung** [gvwilson/teachtogether.tech#189]
The section on Lesson Design: Process discusses Backward Design. I was wondering if it'd be useful to also add Cognitive Task Analysis or Van Merrienboer, et al's 4 component model as other ways to help break things down into learnable pieces?

**Comment by gvwilson** [comment]
I'm not familiar with CTA - I looked at 4C-ID, but I thought it was too heavyweight for this audience.  Happy to be persuaded otherwise - what would authors/instructors do differently/better if they knew about it?
Thanks!
Greg
