### ISSUE TITLE
fix typo in meetings guide

### ISSUE THREAD

**Issue by brainwane** [gvwilson/teachtogether.tech#196]
`teachtogether.tech/tex/meetings.tex` has:

> Every project should end with a post mortem in which you reflect on what you just accomplished and what you could o better next time.

This should be:

> Every project should end with a post mortem in which you reflect on what you just accomplished and what you could do better next time.

This is, in my opinion, a beginner-friendly issue.

**Comment by gvwilson** [comment]
Thanks @brainwane.
