### ISSUE TITLE
Self-contained build proposal

### ISSUE THREAD

**Issue by crlfe** [gvwilson/teachtogether.tech#198]
Was kicking around some build problems with @cetlan (missing font .sty, then my older pandoc not supporting --resource-path). Decided to wrap the whole thing up in Docker to sidestep platform and version conflicts.

Prototype: [edit: moved to https://github.com/crlfe/ttt-docker]
Tested on Linux (Mint 18.3 and 19, so roughly Ubuntu 16.04 and 18.04) so far. Sounds like the dev server isn't visible on Mac or Windows for the moment.

The container doesn't require changes to the build, so there is no rush to merge it. However, I'd like to start the conversation of whether it would be useful to other people, and how we should organize the instructions if so.

**Comment by gvwilson** [comment]
Thanks @crlfe and @Cetlan - I'm working to simplify the build in https://github.com/gvwilson/t/tree/en, partly in order to support multiple languages.  It uses Markdown as the primary source instead of LaTeX, which gets rid of some of the Pandoc issues - is it a step forward?

**Comment by crlfe** [comment]
The markdown-first branch definitely feels positive at a quick read. Believe it removes the need for a brand-new pandoc, so should work at least back to Debian Stretch/Ubuntu 16.04/Mint 18 (hopeful for WSL and MacPorts).

As it might be useful for your build instructions, the packages added in the container are: `build-essential jekyll pandoc python3 python-bibtexparser texlive-bibtex-extra texlive-latex-extra` (with no particular effort to prune things)

python-bibtexparser replaced your pip install. The script that imports bibtexparser had `#!/usr/bin/env python`, which defaults to Python2. Don't know whether anything actually wound up running in Python3, but it all seemed to work.

I'm going to quickly rearrange the container files and instructions to work from a separate directory (will add the updated link here). Linux and Windows hosts appear to work, and I believe Mac has the same limitations as Windows. Propose pausing the container tinkering until after your Markdown refactor, since time will tell whether that produces a larger group of interested collaborators with a wider variety of build problems :)
