### ISSUE TITLE
links to chapters jump out of full page

### ISSUE THREAD

**Issue by steltenpower** [gvwilson/teachtogether.tech#199]

**Comment by gvwilson** [comment]
HI @steltenpower - can you please tell us a bit more about the issue and/or post a screenshot? And can you also please tell us what device/browser you're on? Thanks - Greg

**Comment by steltenpower** [comment]
At main http://teachtogether.tech/ you see at the left a list of links ranging from "Introduction"  to "Design Notes". You might want to see these links changed into anchors ( https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a ) when clicking "Single Page" (just below that list of links) especially for off-line reading purposes.

**Comment by gvwilson** [comment]
Thanks very much @steltenpower - I think I understand. It should be possible to modify the build to do this for the single-page version - I'm making some changes in the `markdown-first` branch, and I'll see if I can fold them in there.
