### ISSUE TITLE
Add material on what to do on the first day

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/teachtogether.tech#205]
https://www.facultyfocus.com/articles/teaching-professor-blog/first-day-of-class-activities-that-create-a-climate-for-learning/

**Comment by yabellini** [comment]
Here is 1  
1 Split in groups of 3 
2 Each person tells something about themselves to the rest
3 Back to the whole group 
4 Person A introduces B.B introduces C.C introduces A. They use something they liked in step 2
5 Repeat

https://twitter.com/yabellini/status/1514234186873421830?s=20&t=fGLVs3TgKOxfuJfyj_ytkw
https://twitter.com/yabellini/status/1514235701612658696?s=20&t=fGLVs3TgKOxfuJfyj_ytkw

**Comment by yabellini** [comment]
Nico: Para algo rápido y presencial, me gusta dividir la clase en dos y ordenarlos en dos filas, cada persona enfrente de otra. Sueno un silbato y cada persona tiene 30 segundos para presentarse frente a la persona que le haya quedado enfrente. Pasado ese minuto, suena silbato, una fila queda quieta, la otra se desplaza un lugar y se repite el procedimiento (la última persona de la fila móvil va al primer lugar). Así hasta que la persona que estaba primera llega al último lugar. Sirve para romper el hielo!

**Comment by yabellini** [comment]
Laura MArtinez Quijano: A mí me gustó el método de mi directora de coro, con un grupo de unas 50 personas que no nos conocíamos de antemano:
nos hizo dividir en grupos por área de origen, nos hizo armar una fila de más jóvenes a mayores (como una pirámide poblacional aplastada), nos hizo agrupar por gustos musicales, por letra de inicio del nombre...
Todos estos ejercicios nos obligaron a hablar rápidamente entre nosotros, todos con todos, e identificar puntos en común!. Por supuesto, las categorías de agrupación pueden cambiar para identificarse mejor con la temática del curso en cuestión...
Además de facilitar la comunicación de todos con todos, requiere un movimiento físico y una ocupación del espacio que están buenos para bajar la ansiedad!

**Comment by yabellini** [comment]
Angela Prince Guerrero: Yo suelo usar una dinámica que se titula ["¿Me conoces?"](https://docs.google.com/document/d/1CmXkv6aauJRLlmNi0NU1g4Lh4YBzLrwr/edit?usp=sharing&ouid=108719182683976229801&rtpof=true&sd=true), comparto instrucciones desglosadas y material necesario. Se vive en 2 etapas:
Se le da a cada persona una hoja con categorías por llenar... dependiendo de la cantidad de alumnos(as) presentes. Tienen un tiempo determinado para llenar las categorías con el nombre de los y las presentes. Todos entregan su hoja completa y se anota el orden en el que lo hicieron.
Teniendo las hojas se van leyendo frente al grupo, la primera hoja con todas las categorías correctas, sin que ningún nombre se repita, gana.
Es un juego que permite que, en primera instancia, todos(as) o la mayoría hablen (los obliga a preguntarse mutuamente cosas), y en segundo lugar, cohesión grupal porque al leer las categorías frente al grupo, todos(as) aprendemos de todos(as) (ya es chamba del maestro(a), hacer la platiquita).
Funciona también a mitad del semestre. https://edhucamexico.blogspot.com/

**Comment by yabellini** [comment]
Issue relacionado: #519

**Comment by yabellini** [comment]
This should be a new appendix we can mention in the section Start With Introductions https://educarencomunidad.tech/en/index.html#s:classroom-setup. We should mention the research on Issue #519 (https://twitter.com/sarahmei/status/1549050661865541634, https://hbr.org/2017/10/research-for-better-brainstorming-tell-an-embarrassing-story) in Start With Introductions section.

**Comment by yabellini** [comment]
Moved to the second edition repo.  Thanks!

**Comment by bew** [comment]
> Moved to the second edition repo. Thanks!

What other repo? 🤔 Could you link to it?

**Comment by yabellini** [comment]
https://github.com/yabellini/t3es2ed
