### ISSUE TITLE
Mention exercism.io for practicing programming against test suites

### ISSUE THREAD

**Issue by katrinleinweber** [gvwilson/teachtogether.tech#209]
Hi Greg!

Just before [`What Misconceptions Do Novices Have?`](https://github.com/gvwilson/teachtogether.tech/blob/e1cb384639a4d20d5a45c0deafdacfaa59da566c/_chapters_en/pck.md#what-misconceptions-do-novices-have-spck-misunderstand) you dedicate a few paragraphs to unit-tests in a learning context. Over in https://github.com/carpentries/lesson-example/issues/163 I suggested to mention [exercism.io](https://exercism.io/) as a useful "learn more" resource. Same suggestion here.

What do you think?

Disclosure: I volunteer as a mentor in the R track there.

**Comment by gvwilson** [comment]
Thanks for the pointer - are there other online teach-yourself-coding sites we could link to as well? And do you know anything about the pedagogical quality of exercism.io's exercises?  https://doi.org/10.1145/3017680.3017728 found that most online coding tutorials were strong on coding and weak on pedagogy; I'd like to recommend something, but I'd like it to be something that is strong on both fronts.

**Comment by katrinleinweber** [comment]
I am not aware that they follow a specific pedagogy, but because they [encourage mentorship, refactoring, "intrinsic motivation" and "reduce unnecessary friction"](https://exercism.io/about-v1-to-v2), I see a lot of overlap to the Carpentries pedagogy. Maybe more than [other coding tutorial sites](https://alternativeto.net/software/exercism/), but I have too little experience with those to judge.

Arguably, exercism.io specifically provides what (I understood) T3 mentions as "One approach to teaching better testing practices is to define a programming problem by providing a set of tests to be passed rather than through a written description".
