### ISSUE TITLE
Learner personas: think of what they don't need to learn

### ISSUE THREAD

**Issue by rkdarst** [gvwilson/teachtogether.tech#223]
One thing I didn't see in lesson design was a consideration of what your learner personas *don't* need to know right away.  When designing lessons, perhaps it's good to spend at least a bit of time thinking which of your brainstorms can be excluded.  I don't remember this anywhere, if it's there somewhere already then this can be closed.  I thought of this because I often see teaching that goes too deep for the situation, which results in people disconnecting.

Sample text to add to Learner Personas section of lesson-design, written from the top of my head and with no research backing it up.  Needs editing and better phrasing at least:

"When designing your learner personas, it may be worth thinking about what they don't need to know (yet), because teaching less can sometimes mean that the student learns more. There are different types of "don't need to know", for example one may not need to know it right now (it is expected to learn/teach it later), or the learner may not ever be expected to learn it.  For both of these, make sure it is not presented as someone *should not* know, but something you *can* know later.  A conclusion is a good place to mention next steps in learning.  Also, can some of these be used as advanced reading/exercises for learners who go faster?"

**Comment by gvwilson** [comment]
This is a really good point, and I'm kicking myself for not thinking of it myself - I've never seen a bullet "what they *don't* need" in a persona, but you're right, it would be very useful to have - thanks.
