### ISSUE TITLE
Talk more about the way teaching intro subjects is denigrated

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/teachtogether.tech#228]
https://twitter.com/RochelleTerman/status/1126642900006252544

**Comment by yabellini** [comment]
RElated to this: https://twitter.com/devjpow/status/1495114689860231169?s=20&t=86Ce76xpGbWnjez3cZoNsA

**Comment by yabellini** [comment]
Hey, @gvwilson This is something I would like us to write together.  You told me that you wanted to add to the introductory chapter a discussion on "translating" scientific developments into understandable language and practical use/examples and why it is important to do so. I understand that you already have a more formed idea than I do about this and it would be great if you could put it into written words. I can join in from there.

**Comment by yabellini** [comment]
Some ideas to discuss this:

* Science becomes more meaningful when its developments and discoveries end up being used and improve people's lives.

* There is an interest in the educational community to use scientific evidence to make their classes more effective.

* In many cases access to this scientific knowledge is difficult, from restricted access to very specialized language, only suitable for experts.

* There are examples that by generating materials that explain these developments and research in a way that is suitable for a more general audience, this information is used.

* The dangers of not being able to "translate" this evidence into something usable and understandable are:
    - Not using it.
    - Educational myths: Misunderstandings and misinterpretations of scientific findings that lead to practical classroom applications that do not work.  Sometimes they are based on confirmation bias, sometimes on marketing campaigns.

The same in Spanish:

* La ciencia termina de tener sentido cuando sus desarrollos y descubrimientos terminan siendo usados y mejoran las videas de las personas.

* Hay un interés de la comunidad educativa de usar evidencia científica para hacer sus clases mas efectivas.

* En muchas ocasiones acceder a ese conocimiento científico es dificil, desde el acceso restringido al lenguaje muy especializado, solo adecuado para expertos.

* Hay ejemplos que generando materiales que expliquen estos desarrollos e investigaciones de forma adecuada para un público más general, esta información se usa.

* Los peligros de no poder "traducir" esta evidencia a algo usable y entendible son:
    - No usarlos.
    - Mitos educativos: Malosentendidos y malasinterpretaciones de hallazgos científicos que llevan a aplicaciones prácticas en el aula que no funcionan.  A veces se basan en el sesgo de confirmaciónb, a veces en campañas de marketin.

See issue #497
