### ISSUE TITLE
Code rubric link broken

### ISSUE THREAD

**Issue by Kim-Ward** [gvwilson/teachtogether.tech#233]
The link to the code quality rubric at http://stgm.nl/quality has gone down. Does anyone have a backup copy?

**Comment by gvwilson** [comment]
I contacted the author, there should be a new link within the week - I'll post it here when I get it. Thanks - Greg

**Comment by gvwilson** [comment]
Martijn has refreshed the page - http://www.stgm.nl/quality/ should now work.
