### ISSUE TITLE
grefdex function is not populating in site build

### ISSUE THREAD

**Issue by ablwr** [gvwilson/teachtogether.tech#234]
Hi!

I noticed the first sentence in the Introduction is unfinished:

"Grassroots groups have sprung up around the world to teach programming, web design, robotics, and other skills to ."

to...? I would have finished it but I am not sure what was intended!

**Comment by ablwr** [comment]
Oh sorry, I see, this is a rendering issue.

`\grefdex{g:free-range-learner}{free-range learners}{free-range learner}` is not rendering on the webpage-generated version of this site, and this seems to be the case in other parts of the codebase. I will update the issue and check to see it's not a duplicate.

**Comment by gvwilson** [comment]
Good catch - thank you.

**Comment by ablwr** [comment]
thank you, I look forward to learning from this document!
