### ISSUE TITLE
ego depletion is probably not a real thing

### ISSUE THREAD

**Issue by RMHogervorst** [gvwilson/teachtogether.tech#235]
Greg, I love this book. I read it slowly to get the best out of it, I read a small thingy in chapter about individual learning, in the box:" when you just can't say no"

Studies in ego depletion don't seem to hold up, I've added a link to "A Multilab Preregistered Replication of the Ego-Depletion Effect " from 2016 that shows they can not replicate the ego depletion effect.  
https://journals.sagepub.com/doi/full/10.1177/1745691616652873

So maybe this should be excluded from the book? 
Cheers, Roel

**Comment by gvwilson** [comment]
Thanks Roel - I've folded it in.
