### ISSUE TITLE
In "Using This Material": what does it take to teach this? (bootstrapping)

### ISSUE THREAD

**Issue by brainwane** [gvwilson/teachtogether.tech#238]
Hi @gvwilson!

Some folks are interested in getting together in person to work through this curriculum. I looked at [the "Using This Material" section](http://teachtogether.tech/#s:joining-using) and I think I have a bootstrapping question: what level of teaching skill/experience is necessary to usefully lead this? Maybe the set of people who would be best at leading this would be the set of people who have led Carpentries instructor training?

Sorry for the less-coherent-than-I'd-like question.

Thanks!

**Comment by brainwane** [comment]
My current understanding is:

* interested people working through the material together in a peer-teaching way is better than nothing
* certified Carpentries instructors are reasonable choices to teach the material
* people with Carpentries instructor training + community organizing or similar relevant experience are even better
* people who have trained other instructors in the past are even better than that
* Greg's the best choice if that's possible

**Comment by gvwilson** [comment]
Hell of a world we live in if I'm the best choice for _anything_ :-)
