### ISSUE TITLE
bad internal links

### ISSUE THREAD

**Issue by daveloyall** [gvwilson/teachtogether.tech#239]
The following internal links (links from the book to itself) are broken on the live site today.

* http://teachtogether.tech/#s:chunking
* http://teachtogether.tech/#s:memory
* http://teachtogether.tech/#s:conduct
* http://teachtogether.tech/#s:joining

There may be others; I didn't check.

p.s. I like your book.  Great work!

**Comment by gvwilson** [comment]
Thanks for the bug report @daveloyall - I *think* it's fixed now, though there seems to be some weird caching issues. Can you please open an anonymous tab in your browser and let me know?

**Comment by daveloyall** [comment]
Yep, it's fixed.
