### ISSUE TITLE
Page layout breaks on mobile

### ISSUE THREAD

**Issue by pwmarcz** [gvwilson/teachtogether.tech#241]
The page layout, with separate scrollable sections, breaks badly on mobile. Here is a screenshot from Chrome on Android:

![Screenshot_20190928-155424_Chrome](https://user-images.githubusercontent.com/468495/65817537-86c23100-e208-11e9-994b-a5a57a4cbbc3.jpg)

The top menu stays on the screen while I scroll the content in a small bottom area.

I suggest making the page non-scrollable on mobile layouts.

**Comment by gvwilson** [comment]
Thanks Pawel - that's beyond my understanding of CSS, so if you can send a PR with the right properties (if that's the right word) I'd be grateful.

**Comment by pwmarcz** [comment]
I'll try!

**Comment by pwmarcz** [comment]
Fixed with https://github.com/gvwilson/teachtogether.tech/pull/243
