### ISSUE TITLE
Glossary contains definitions but not the terms that are being defined

### ISSUE THREAD

**Issue by mattes3** [gvwilson/teachtogether.tech#257]
Thanks for the fantastic book!

When reading the HTML version, I noticed that in the glossary, only the explanation for each term is present, not the term itself. The term itself is missing.

Example: The first item in the glossary looks like this:

> Someone who has never encountered concepts or material before. The term is used in distinction to false beginner.

It should look like this:

> **Absolute beginner:** Someone who has never encountered concepts or material before. The term is used in distinction to false beginner.

All the terms are missing, in each and every glossary entry.

So there must be something wrong in the LaTex configuration, right? I'm not a LaTex guy, so I don't know.

**Comment by gvwilson** [comment]
Thanks for catching that - it used to be correct, so I must have broken something recently. I'll try to get a fix in today.

**Comment by gvwilson** [comment]
Fixed in 50aa20b0 - thank you again.

**Comment by mattes3** [comment]
Works! Thanks for the quick response! 👍
