### ISSUE TITLE
Add words to glossary

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#271]
There are dictionary-defined words that are used in more than one way (eg, Experto/a, Persona experta). We need to decide what to do. 
Proposal:  We define in the first appearance (in this case Experto/a) and in the second appearance (in this case Persona Experta) we indicate to see [first appearance] (in this case Experto/a).

**Comment by nmorandeira** [comment]
I'd add to the glossary all those words that are not translated (listed at the Readme)

**Comment by nmorandeira** [comment]
Test 
https://github.com/yabellini/T3Glossary/issues/2#issue-785354934

**Comment by nmorandeira** [comment]
scaffolding - No traducido; capítulo architecture.tex

**Comment by nmorandeira** [comment]
ver: indentación o sangrías
ejemplo, architecture.tex

**Comment by nmorandeira** [comment]
misconception > concepto erróneo

**Comment by nmorandeira** [comment]
Para chequear, me lo tira al compilar:

**Glossary missing**
  g:situado-learning
  
**Glossary unused**
  g:end-user-teacher
  g:teaching-to-the-test

**Bibliography missing**
   Wilk2011

**Bibliography unused**
  Holl1960
  Scot1987
  Wlod2017

**Comment by nmorandeira** [comment]
Check terms of the alphabetic index: are they in the bilingual glossary?

**Comment by yabellini** [comment]
Todos los términos fueron agregados y definidos.  Nati chequeó el indice alfabético.  Queda actualizar el glosario bilingüe pero eso está en otro repo.
