### ISSUE TITLE
International names list - regional name list

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#272]
We need to decide whether we go for an international list of names or we go for a regional one. I found names of fictional people in two chapters:
Chapter: Introduction
    Emily
    Moshe
    Samira
    Gene
    Jorge 
Chapter: Building a Community of Practice
    Anna
    Catherine
    Frank
    Hediyeh
    Ken
    Melissa
    Raj
**International list **
We talk about include some LatinAmerican-Hispanic/Japanese/Korean/Chinese/Indonesian name so we have the same international list of names for the English and the Spanish version of the book. 
We suggested: David (replace Moshe), Cristian (replace Jorge - the hispanic J is difficult for English speakers) Ali, Yuriko, Ana, Catalina, Fernando, Andrea, René, Melisa, Roberto.  Samira works well in both languages.
**Regional list** 
   Ana
   Catalina
   David
   Emilia
   Fernando 
   Andrea
   René
   Melisa
   Roberto
   Samira
   Jorge
   Juan José

**Comment by yabellini** [comment]
In the Community Chapter we are using the regional names.

**Comment by nmorandeira** [comment]
check Jane - chapter classroom

**Comment by yabellini** [comment]
We are going to use regional names.  I added the list on the readme.md in the Spanish translation.

**Comment by nmorandeira** [comment]
classroom.tex, changed Jane x Andrea https://github.com/gvwilson/teachtogether.tech/pull/317/commits/e19d43ba20ac35daadff470490c60ce5debb1778

**Comment by nmorandeira** [comment]
community.tex, I corrected two names according to the readme.md https://github.com/gvwilson/teachtogether.tech/commit/5cec1f65afd9b387f706756f192ab37fe22a5424

**Comment by nmorandeira** [comment]
I close the issue! @yabellini
