### ISSUE TITLE
Add the translate version of dedication to the Spanish version

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#274]
Add the translated version of dedication to the Spanish version: https://github.com/gvwilson/teachtogether.tech/blob/master/es/dedication.tex

**Comment by natastro** [comment]
Hello! Happy to help with Spanish translation if needed 😄 Thank you!

**Comment by yabellini** [comment]
@natastro can you write me to yabellini@gmail.com 😀

**Comment by nmorandeira** [comment]
@yabellini I don't understand this issue ;)

**Comment by yabellini** [comment]
The Dedication was not part of the book and the web in the first PDFs and HTML.  If this is now on the web page and the PDF, this issue can be closed.

**Comment by nmorandeira** [comment]
- Dedication is already part of the html
- I added it to the PDF, see the PR
