### ISSUE TITLE
Spanish Title

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#285]
English title is very nice, the literal translation into Spanish is not sooo cool, 
We want to try to think of alternatives in Spanish that obviously convey the same message, but that can be a nice combination of words.

The title now is: Enseñar tecnología en comunidad.

Other options?

**Comment by paocorrales** [comment]
@eliocamp also suggested "Enseñar herramientas entre todos" or "Enseñar herramientas en comunidad".

I think "herramientas" is a better word to reflect the content of the book and can be better receive by Spanish-speakers.

**Comment by yabellini** [comment]
Ya tenemos hex con Enseñar tecnología en comunidad.
