### ISSUE TITLE
Review the use of non-sexist language

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#294]
Review the use of non-sexist language in all chapters, including diagrams and figures:

- [x] Dedication _- las/los_
- [x] The Rules _- los/las_
- [x] Sobre la traducción _- neutro_
- [x] Introduction _- las/los_
- [x] Mental Models and Formative Assessment _- los/las_
- [x] Expertise and Memory _- las/los_
- [x] Cognitive Architecture _- los/las_
- [x] Individual Learning _- las/los_
- [x] A Lesson Design Process _- los/las_
- [x] Pedagogical Content Knowledge _- las/los_
- [x] Teaching as a Performance Art _- los/las_
- [x] In the Classroom _- las/los_
- [x] Motivation and Demotivation _- los/las_
- [x] Teaching Online _- las/los_
- [x] Exercise Types _- los/las_
- [x] Building a Community of Practice _- las/los_
- [x] Outreach _- los/las_
- [x] Why I Teach _- las/los_
- [x] License _- los/las_
- [x] Code of Conduct _- las/los_
- [x] Joining Our Community _- los/las_
- [x] Glossary _- las/los_
- [x] Meetings, Meetings, Meetings _- los/las_
- [x] Checklists and Templates _- las/los_
- [x] Example Concept Maps _- los/las_
- [x] Chunking Exercise Solution _- las/los_
- [x] References (notes) _- los/las_

**Comment by nmorandeira** [comment]
I added "Sobre la traducción". It's revised :)

**Comment by nmorandeira** [comment]
The last chapter was revised!! glossary.tex 
I close the issue
