### ISSUE TITLE
Check titles and subtitles capitalization

### ISSUE THREAD

**Issue by nmorandeira** [gvwilson/teachtogether.tech#297]
In the Spanish translation, we don't use capital letters (mayúsculas) for all the words in the title, just the 1st one

**Comment by yabellini** [comment]
Chapters:
- [x] Dedication 
- [x] The Rules 
- [x] Sobre la traducción
- [x] Introduction 
- [x] Mental Models and Formative Assessment 
- [x] Expertise and Memory 
- [x] Cognitive Architecture 
- [x] Individual Learning 
- [x] A Lesson Design Process 
- [x] Pedagogical Content Knowledge 
- [x] Teaching as a Performance Art 
- [ ] In the Classroom 
- [ ] Motivation and Demotivation 
- [ ] Teaching Online 
- [ ] Exercise Types 
- [ ] Building a Community of Practice 
- [ ] Outreach 
- [ ] Why I Teach 
- [ ] License 
- [ ] Code of Conduct 
- [ ] Joining Our Community 
- [ ] Glossary 
- [ ] Meetings, Meetings, Meetings 
- [ ] Checklists and Templates 
- [ ] Example Concept Maps 
- [ ] Chunking Exercise Solution 
- [ ] References (notes)
