### ISSUE TITLE
Translate "References" (Referencias) in html version

### ISSUE THREAD

**Issue by nmorandeira** [gvwilson/teachtogether.tech#298]
In the online html version, References should be translated into Spanish as "Referencias" (https://teachtogether.tech/es/index.html#references)

**Comment by nmorandeira** [comment]
Also, most of the references have comments on their main contributions. These comments need a translation

**Comment by yabellini** [comment]
We also need to get LaTeX to translate: chapters as "capítulos", sections as "sección", figures as "figures", appendices as "apéndices" and add the articles "el" / "al" when the reference to this section/elements of the book are not in parentheses.

**Comment by nmorandeira** [comment]
"el" / "al" should be added manually by us? (I guess). It doesn't seem a Latex fix

**Comment by nmorandeira** [comment]
"Appendices": I suggest "Anexos"

**Comment by paocorrales** [comment]
The line `\usepackage[spanish]{babel}` should do the translation the labels of "chapter" and everything else to Spanish. It's not working?

**Comment by nmorandeira** [comment]
No, it doesn't work. Maybe related to ` \documentclass[]{../tex/krantz} `? (I get some warnings related to this when I compile)

**Comment by nmorandeira** [comment]
No entiendo mucho de Latex, pero dejo otra warning que me salta y que parece relacionada con el problema
```
Package caption Warning: Unsupported document class (or package) detected,
(caption)                usage of the caption package is not recommended.
See the caption package documentation for explanation.
```
Por lo que entendí de aquí, _caption_ es compatible con algunos _document class_ y no con otros:
https://tex.stackexchange.com/questions/34579/is-there-really-something-wrong-with-using-the-caption-package-for-continuedflo

El warning referido a krantz si mal no recuerdo ya lo miramos con Greg y a él no le llamó la atención, es este:
```
LaTeX Warning: You have requested document class `../tex/krantz',
               but the document class provides `krantz'.
```

**Comment by yabellini** [comment]
In my PDF version References is translate as Bibliografía, but not the rest of the section mention in a previous comment.

**Comment by nmorandeira** [comment]
My pdf version is like yours
> In my PDF version References is translate as Bibliografía, but not the rest of the section mention in a previous comment.

**Comment by nmorandeira** [comment]
I found what is happening!
Check these two files: 
https://github.com/gvwilson/teachtogether.tech/blob/master/tex/html-settings.tex
https://github.com/gvwilson/teachtogether.tech/blob/master/tex/pdf-settings.tex

These lines change the captions:

`% Chapters, sections, and appendices with labels.
\newcommand{\chaplbl}[2]{\chapter{#1}\label{#2}}
\newcommand{\seclbl}[2]{\section{#1}\label{#2}}
\newcommand{\appref}[1]{Appendix~\ref{#1}}
\newcommand{\chapref}[1]{Chapter~\ref{#1}}
\newcommand{\figref}[1]{Figure~\ref{#1}}
\newcommand{\secref}[1]{Section~\ref{#1}}`

I tried replacing them and it works (except for: *Reference* in HTML version, which is edited in another file).
So now I added those lines in `pdf-settings.tex` and `html-settings.tex`, but they are commented.
If you un-comment the lines, and comment the English labels, the fix works. 
Needs an automatized language selection; maybe in those files or in `pre-pandoc.py`. I couldn't do that.

This was tested in this PR: https://github.com/gvwilson/teachtogether.tech/pull/319

**Comment by nmorandeira** [comment]
I added these commented lines to `html-settings.tex` and `pdf-settings.tex`, in a branch

```
% Spanish version
%\newcommand{\chaplbl}[2]{\chapter{#1}\label{#2}}
%\newcommand{\seclbl}[2]{\section{#1}\label{#2}}
%\newcommand{\appref}[1]{Anexo~\ref{#1}}
%\newcommand{\chapref}[1]{Capítulo~\ref{#1}}
%\newcommand{\figref}[1]{Figura~\ref{#1}}
%\newcommand{\secref}[1]{Sección~\ref{#1}}
```
