### ISSUE TITLE
Check the recipient of the Exercises

### ISSUE THREAD

**Issue by nmorandeira** [gvwilson/teachtogether.tech#299]
This is partly related to [this issue](https://github.com/gvwilson/teachtogether.tech/issues/256), which is already solved in the Spanish version. Now I add a new issue to revise the Spanish version thoroughly:
Some of the exercises are written for the teacher: "_Haz que tu estudiante resuelva este ejercicio_", while others are written for the student "_Con tu pareja, resuelve este ejercicio_". E.g. chapter "Tipos de ejercicios" (Exercise Types)

**Comment by yabellini** [comment]
Do we made the proper changes in Spanish Nati?, Can I close this issue?

**Comment by nmorandeira** [comment]
This is yet to be revised. I had made comments on the column "Sujeto de los ejercicios" in our _Repartija_ sheet

**Comment by nmorandeira** [comment]
I've changed three exercises, each of them in one of these chapters: individual.tex, motivation.tex, exercise.tex. PR https://github.com/gvwilson/teachtogether.tech/pull/394
Now, the recipient of the exercises is a learner doing the exercise (who may be learning how to teach, but he/she is not teaching while doing the exercise). This is corrected throughout the Spanish version. Maybe this edition can be transferred to the English version, but I'm commenting that in another issue https://github.com/gvwilson/teachtogether.tech/issues/256 and closing this one.
