### ISSUE TITLE
Frisian "Lengua frisona": suggestion of language replacement for [es]

### ISSUE THREAD

**Issue by nmorandeira** [gvwilson/teachtogether.tech#305]
In chapter _arquitecture.tex_, subsection "Problemas de Parsons" (Parsons Problems)), the example of translation into Frisian is not familiar and difficult to understand. I even didn't know the existence of Frisian before reading the book. Also, readers would need to know English in order to understand the example.

I suggest changing the Parsons Problem and translating into "Catalán", which may also be a good message that Spanish ("castellano") is not the only language spoken in the Iberic Peninsula. Or maybe Portuguese...
(Although is difficult to find grammatical changes in word orders; word order is not as important in Spanish as in English).

This change would need a change in _fisian.png_ too.

**Comment by yabellini** [comment]
I like it! I have that example using French but I love the idea of catalán.  
I can change the picture if you give me the words.

**Comment by nmorandeira** [comment]
_¿Cómo está tu rodilla hoy?_  (Castellano)
is translated:
_Com està el teu genoll avui?_ (Catalán)

Consulted with my friend Sarah Rodríguez! G00gle translator seems to work awful, she suggests using this translator: https://www.softcatala.org/traductor/

draft of the scheme in the next comment

**Comment by nmorandeira** [comment]
draft, to replace _frisian.png_

![photo4934129752327956715](https://user-images.githubusercontent.com/6751201/105729933-7f01c200-5f0c-11eb-8157-c7428355e28b.jpg)

**Comment by yabellini** [comment]
Done!
