### ISSUE TITLE
Exercises - uniformize translations on the number of people

### ISSUE THREAD

**Issue by nmorandeira** [gvwilson/teachtogether.tech#308]
Related to [this issue](https://github.com/gvwilson/teachtogether.tech/issues/284): translations on how to refer to the number of people need to be consistent over the book.
- **Individual** ó Individuos?
- **Parejas** ó De a pares?
- **Grupos pequeños**
- Toda la clase ó **Clase completa**?

My vote is in bold letters :)

**Comment by yabellini** [comment]
Agree with you in all except that I like more "Toda la clase" but I can live with Clase completa 😊.

**Comment by nmorandeira** [comment]
I can live with "Toda la clase" too!! (and I think that most of the translators preferred that way)

**Comment by nmorandeira** [comment]
Consensus:

- Individual is translated as  **Individual**
- Pairs is translated as **Parejas**
- Small groups is translated as **Grupos pequeños**
- Whole class is translated as **Toda la clase**

 (maybe should be added to Readme?)

**Comment by yabellini** [comment]
Done!

**Comment by yabellini** [comment]
Chapters to check:

- [ ] Introduction 
- [ ] Mental Models and Formative Assessment 
- [ ] Expertise and Memory 
- [ ] Cognitive Architecture 
- [ ] Individual Learning 
- [ ] A Lesson Design Process 
- [ ] Pedagogical Content Knowledge 
- [ ] Teaching as a Performance Art
- [ ] In the Classroom 
- [ ] Motivation and Demotivation 
- [ ] Teaching Online 
- [ ] Exercise Types 
- [ ] Building a Community of Practice 
- [ ] Outreach 
- [ ] Joining Our Community
