### ISSUE TITLE
[Question] I'm intrigued by the concepts "authentic tasks" and "minimal manuals". Should I read the references to learn more?

### ISSUE THREAD

**Issue by simkimsia** [gvwilson/teachtogether.tech#311]
I came across [authentic tasks](https://teachtogether.tech/en/#s:motivation-authentic) and minimal manuals in the website.

Should I read all the references that these two sections cover?

Eg. https://teachtogether.tech/en/#ref-Carr2014

**Comment by gvwilson** [comment]
Depends how much time you have - the minimal manual approach is good for technical reference documentation, but not necessarily for this kind of tutorial.
