### ISSUE TITLE
Marca de género on las conjunciones "al" y "del"

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#312]
La lectura del lenguaje no sexista con las conjunciones "al" y "del" es complicado. **Hay que ver qué hacer en todos los capítulos.**

* Caso de capítulo los/las: "al/a la docente" "del/de la docente". (*)
   -  Alternativa 1: dejar sólo el masculino "Al docente"
   -  Alternativa 2: dejar el masculino en la conjunción, pero no en el sustantivo si este tiene marca de género: "Al usuario/a"
   -  Alternativa 3: desdoblar "al docente o a la docente".

* Caso de capítulo las/los (empeora!!): "a la/al docente" "de la/del docente".
   - Alternativa 1: dejar sólo el femenino "A la docente"
   - Alternativa 2: dejar el femenino en el artículo, pero no en el sustantivo si este tiene marca de género: "A la usuaria/o"
   - Alternativa 3: desdoblar "a la docente o el docente".

Nati: Quizás es mejor la Alternativa 1 o 2??
Yani: voto por la 2 o 3.
Resultado: usaremos la opción 2.

**Comment by nmorandeira** [comment]
de acuerdo!
después hay que agregarlo al Readme, por si pasa en otros idiomas (en portugués seguro).

**Comment by yabellini** [comment]
Ya lo agregué a las reglas en el README.
