### ISSUE TITLE
Alphabetic index in the pdf book [es]

### ISSUE THREAD

**Issue by nmorandeira** [gvwilson/teachtogether.tech#316]
What should we do with the alphabetic index? Now it has some terms in English and some in Spanish.

Should we look for the English terms and translate them? I think we have kept some terms in English during the translations and revisions, because we confounded the tags with other Latex elements such as index entrances ---at least this happened to me!

Or should we forget about them? The alphabetic index only compiles in the pdf version, not in the HTML.

May be this is not important now, but can be important if we publish a paper-physic book.

**Comment by yabellini** [comment]
I will search and translate if we agree in a translation. I agree that we can being confuse because LaTeX.

**Comment by nmorandeira** [comment]
I translated the index labels of all the chapters with a merged 1st revision version

**Comment by nmorandeira** [comment]
I close it with this PR https://github.com/gvwilson/teachtogether.tech/pull/392
