### ISSUE TITLE
Add Spanish video for live coding

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#329]
Add Spanish (and on-line) video for live coding to the chapter "Teaching as a Performance Art":

How to teach bad using live coding: https://youtu.be/i4WhKJ59_5M,
How to teach well using live coding: https://youtu.be/R2ob_YUp0yw

**Comment by nmorandeira** [comment]
qué excelente!! genia Pao

**Comment by nmorandeira** [comment]
Agregados! 

```
Mira los videos de \hreffoot{https://youtu.be/i4WhKJ59_5M}{programación en vivo mal desarrollada}
y \hreffoot{https://youtu.be/R2ob_YUp0yw}{bien desarrollada}
```

Queda cambiar un link, quizás ahí sí va el de Laura para The Carpentries? (no parece ser específico de live coding)
```
En grupo,
miren \hreffoot{https://www.youtube.com/watch?v=-ApVt04rB4U}{este video de mala enseñanza}
```

**Comment by yabellini** [comment]
Tengo que pedir permiso, la otra es ver si podemos agregar subtítulos en español la video de Greg.

**Comment by yabellini** [comment]
Recién mandé los subtítulos en español del video de Greg enseñando mal a Carpentries y ellos van a subirlos, asi que va a tener los subtítulos en español.  El video es tremendo y leer lo que dice en español, madre mia...creo que tiene el efecto deseado.

**Comment by nmorandeira** [comment]
excelente!

**Comment by nmorandeira** [comment]
cuando estén los subs, hay que agregar algo así:

_En grupo,
miren \hreffoot{https://www.youtube.com/watch?v=-ApVt04rB4U}{este video de mala enseñanza} (en inglés, subtitulado al español ---activa los subtítulos al ingresar al link)._

**Comment by yabellini** [comment]
Ya agregué ese texto.  Están teniendo problemas para acceder a ese canal de youtube y subir los subtítulos.  Apenas estén disponibles cierro este issue.

**Comment by yabellini** [comment]
Listo los subtíutlos, cambió el link del video porque lo cambiaron de canal de Youtube: https://www.youtube.com/watch?v=jxgMVwQamO0

**Comment by yabellini** [comment]
Link updated in Spanish version.
