### ISSUE TITLE
Problem with citation formatting & hyperlinks

### ISSUE THREAD

**Issue by brainwane** [gvwilson/teachtogether.tech#337]
A few citations in ["What to Read Instead"](http://teachtogether.tech/en/index.html#s:intro-instead) do not show up properly, starting with

https://github.com/gvwilson/teachtogether.tech/blob/9ecd8767bd453a002757c26cdb1a394074892893/en/intro.tex#L113

which shows up in the online text as

> If you are in a hurry or want a taste of what this book will cover, presents ten evidence-based tips for teaching computing.

**Comment by brainwane** [comment]
I also see this problem in https://github.com/gvwilson/teachtogether.tech/blob/9ecd8767bd453a002757c26cdb1a394074892893/en/models.tex#L5

which shows up in the online text as

> The first task in teaching is to figure out who your learners are. Our approach is based on the work of researchers like Patricia Benner, who studied how nurses progress from novice to expert .

The problem may be in several more places in the text.

**Comment by brainwane** [comment]
Found another example in https://github.com/gvwilson/teachtogether.tech/blob/9ecd8767bd453a002757c26cdb1a394074892893/en/models.tex#L280 

My guess: it's probably the tilde in the `~\cite{}` syntax that's causing the trouble.

@gvwilson I'm guessing that it's not particularly helpful for me to find and add more examples as I read, so I'll stop here; please tell me if I'm wrong.

**Comment by nmorandeira** [comment]
Yesterday I also detected these two examples in pck.tex
Luxt2017, Viha2014 (exercises: "What are you teaching?" and "Beneficial activities")

Missing references occur both in English and Spanish HTML versions

**Comment by nmorandeira** [comment]
Greg, all the Reference section is missing from the HTML (English and Spanish version): https://teachtogether.tech/en/index.html#references > there are only 13 footnotes
https://teachtogether.tech/es/index.html#references > nothing
@gvwilson

**Comment by nmorandeira** [comment]
Just one more, I don't know whether it's related to this issue or is due to another problem.

In online.tex:
HTML version: 
`"Looking even further ahead, [Ijss2000] found that real-time feedback on in-class exercises using learners’ own mobile devices improved concept retention and learner engagement while reducing failure rates."`

but in the .tex file, the text is much longer (the text between the two references was removed):

```
Looking even further ahead,
\cite{Ijss2000} identified four levels of online presence,
from realism (we can't tell the difference)
through immersion (we forget the difference)
and involvement (we're engaged but aware of the difference)
to suspension of disbelief (we are doing most of the work).
Crucially,
they distinguish physical presence,
which is the sense of actually being somewhere,
and social presence, which is the sense of being with others.
The latter is more important in most learning situations,
and again,
we can foster it by using learners' everyday technology in the classroom.
For example,
\cite{Deb2018} found that real-time feedback on in-class exercises
using learners' own mobile devices
improved concept retention and learner engagement while reducing failure rates.

```
https://github.com/gvwilson/teachtogether.tech/blob/9ecd8767bd453a002757c26cdb1a394074892893/en/online.tex#L603

**Comment by gvwilson** [comment]
I think this is now fixed (a regular expression bug was gobbling too much text). Can you please have a look and let me know?

**Comment by nmorandeira** [comment]
great! In-text citations are corrected.
Not yet the Reference section: https://github.com/gvwilson/teachtogether.tech/issues/337#issuecomment-799796580

**Comment by brainwane** [comment]
@gvwilson I concur with @nmorandeira. It looks like the inline citations now display their citation slugs properly, e.g., 

> `Our approach is based on the work of researchers like Patricia Benner, who studied how nurses progress from novice to expert [Benn2000].` 

However, the hyperlink http://teachtogether.tech/en/index.html#ref-Benn2000 doesn't direct to any anchor tag on the page, and http://teachtogether.tech/en/index.html#references doesn't include any of the scholarly citations.

**Comment by nmorandeira** [comment]
This issue seems to be solved
