### ISSUE TITLE
Check alt-tex in pictures in the web

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#346]
I didn't find alt-text in the pictures of the Mental Models chapter in the Spanish version.  
We need to check the rest of the chapters.

**Comment by nmorandeira** [comment]
how is alt-text added in Latex? For example, here 🤔 :

\figpdf{figures/bathtub.pdf}{Hielo en un recipiente}{f:models-bathtub}

**Comment by yabellini** [comment]
Es una de las preguntas para el contacto que nos dio Greg.  Yo aún no tuve tiempo de armarle el mail con las y los archivos correspondientes.

**Comment by nmorandeira** [comment]
Conceptual maps are fully inaccessible to blind persons. And it seems difficult to solve with alt-texts

**Comment by nmorandeira** [comment]
From here: https://authors.acm.org/journals/how-to-write-alt-text-and-why

> LaTeX users can use the command \Description[<short description>]{<long description>} inside every figure, teaserfigure, marginfigure, or table environment to provide a description of the image(s) used in the figure. Unlike \caption, which is used alongside the image, \Description is intended to be used instead of the image, for example,
> 
> \begin{figure}
>     \centering
>     \includegraphics{voltage}
>    \Description[A bell-like histogram]{A bell-like histogram centered at $0.5$~V with most measurements between $0.2$~V and $0.8$~V}
>    \caption{Histogram of the measurements of voltage}
>    \label{fig:voltage}
> \end{figure}

**Comment by yabellini** [comment]
What I do with concept maps is describe them. As in this post: https://learning-learnr.netlify.app/post/learnr_concept_map/
I can do that for the ones in T3. We can ask Greg he check this description.

**Comment by gvwilson** [comment]
I didn't know about \Description - happy to translate Spanish descriptions of figures back into English and figure out how to get it into HTML. Thank you.

**Comment by nmorandeira** [comment]
Let's try how it looks in one of the figures of models.tex @yabellini ! :)  And maybe we can test on a screen reader app

**Comment by yabellini** [comment]
Ok, here is the alt-text for the 3 figures in models.tex, how we add to the latex?.  Here is the latex for add a figure now: 
\figpdf{figures/bathtub.pdf}{Hielo en un recipiente}{f:models-bathtub}, where we should add the \Description?

- Agua-Water:

ES: Esquema de un recipiente con agua y un bloque de hielo.
EN: Scheme of a container with water and a block of ice.

- Evaluación - Evaluation:

ES: el mapa conceptual presenta los conceptos y relaciones principales entre esos conceptos relacionados a las evaluaciones formativas.
Una evaluación formativa es rápida e inequívoca de manera tal que es escalable. También tiene poder de diagnóstico para identificar vacíos y conceptos erróneos que pueden tener los/las estudiantes y que los docentes aclaran usando la retroalimentación que les dan las evaluaciones formativas. Esa retroalimentación también puede ser utilizada por los/las docentes para decidir si un tema se debe revisar, se puede saltear porque ya se conoce o se puede proceder porque se entendió.

EN: this concept map presents the main concepts and relationships between those concepts related to formative assessments.
A formative assessment is quick and clear so it is scalable. It also has diagnostic power to identify gaps and misconceptions that students may have and that teachers clarify using the feedback from formative assessments. This feedback can also be used by teachers to decide if a topic should be revisited, it can be skipped because it is already known or it can proceed because it was understood.

- Modelos mentales - mental models

ES: el mapa conceptual presenta los conceptos y relaciones principales entre esos conceptos relacionados a los conceptos mentales.
Los modelos mentales deben ser útiles y no necesitan ser completos o correctos. Cuando una persona novata (que puede tener una falsa confianza) desarrolla un modelo mental se convierte en un practicante competente.
Los mapas conceptuales se usan para representar un modelo mental por medio de nodos que representan conceptos y enlaces que representan relaciones. Las relaciones habilitan recordar los conceptos. Estos mapas también ayudan a diseñar una lección siguiendo las relaciones.

EN: the concept map presents the main concepts and relationships between those concepts related to mental concepts.
Mental models must be useful and do not need to be complete or correct. When a novice (who may have false confidence) develops a mental model, becomes a competent practitioner.
Concept maps are used to represent a mental model through nodes that represent concepts and links that represent relationships. Relationships enable you to recall concepts. These maps also help design a lesson by following the relationships.

**Comment by gvwilson** [comment]
I can add another field to the `\figpdf` command to take the `Description` text and insert it in the right place. I will make that an optional argument (so that you don't have to have descriptions for all figures). Later today?

**Comment by yabellini** [comment]
Great. Thank you.

**Comment by yabellini** [comment]
I create an R script that takes the index.html and adds the alt tag to every picture with the corresponding text.  It is a temporary solution until Greg can add the alt-text from LaTeX.
