### ISSUE TITLE
Tools in on-line teaching

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#348]
I use it a lot, but I dislike the idea of mentioning _Slack_ as a choice to build a space to interact with students.  It is not accessible at all. The last company decision about allowing DM between workspaces (and you have to pay to turn this off) without thinking about the consequences for some people of this functionality is horrible.
I will remove and perhaps include others like Discord or Telegram.

For collaborative note-taking, I will add HackMD and Etherpad. These are the most accessible ones, and even hackMD don't work well with more than 10 people working at the same time it is one of the most accessible one.

**Comment by gvwilson** [comment]
:+1: I no longer recommend Etherpad - the code base is very tangled, I don't know if it's being maintained, and I have been told there are security issues (but I have not verified this myself).

**Comment by yabellini** [comment]
this is not a good idea? https://pad.riseup.net/

**Comment by yabellini** [comment]
I remove Slack and added the other software mention here.
