### ISSUE TITLE
Use Spanish cover in Spanish HTML

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#363]
When building the website, use the t3-front-small-es.png in the Spanish version with the alt-tex="Enseñar Tecnología en Comunidad"

**Comment by yabellini** [comment]
I need to be sure that Greg change the way he build the HTML and use the Spanish cover, I change the one that we see now "by hand".  That why I re open the issue.-

**Comment by gvwilson** [comment]
When I look at https://teachtogether.tech/ I see the Spanish cover on the site home page /index.html and also in the Spanish directory /es/index.html, so I think it's working (?).

**Comment by yabellini** [comment]
I am talking about this index: https://teachtogether.tech/es/index.html

**Comment by yabellini** [comment]
I change that in the HTML.  When you build the site, do you change that index or you don't touch that page? I have the impression that I had changed that cover and in the last rebuilds of the site, the picture inside the Spanish version returned to the link to the cover in English.  But I don't know how this works, so If you said this is done we can close the issue.

**Comment by yabellini** [comment]
As I suspected, when the site is rebuilt, the Spanish cover in https://teachtogether.tech/es/index.html is replaced with the English cover.  Can you please change that Greg?.  Thank you!

**Comment by gvwilson** [comment]
Closed in 5193d8d29
