### ISSUE TITLE
Document Type 

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#371]
https://third-bit.com/2019/08/08/documentation-types/

https://yabellini.netlify.app/es/post/que_documentacion_y_cuando/

**Comment by gvwilson** [comment]
I am less confident in the taxonomy of documentation types than I was when I wrote the post - it makes sense, but that doesn't mean it is right.

**Comment by yabellini** [comment]
Ok, so how about we talk a little more about teaching how to search help and how to read that help?
