### ISSUE TITLE
Alt-text for figures chapter models.tex

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#380]
- [x] Agua: Esquema de un recipiente con agua y un bloque de hielo.
- [x] Evaluación: el mapa conceptual presenta los conceptos y relaciones principales entre esos conceptos relacionados a las evaluaciones formativas.  Una evaluación formativa es rápida e inequívoca de manera tal que es escalable. También tiene poder de diagnóstico para identificar vacíos y conceptos erróneos que pueden tener los/las estudiantes y que los docentes aclaran usando la retroalimentación que les dan las evaluaciones formativas. Esa retroalimentación también puede ser utilizada por los/las docentes para decidir si un tema se debe revisar, se puede saltear porque ya se conoce o se puede proceder porque se entendió.
- [x] Modelos mentales: el mapa conceptual presenta los conceptos y relaciones principales entre esos conceptos relacionados a los modelos mentales. Los modelos mentales deben ser útiles y no necesitan ser completos o correctos. Cuando una persona novata (que puede tener una falsa confianza) desarrolla un modelo mental se convierte en un practicante competente.
Los mapas conceptuales se usan para representar un modelo mental por medio de nodos que representan conceptos y enlaces que representan relaciones. Las relaciones habilitan recordar los conceptos. Estos mapas también ayudan a diseñar una lección siguiendo las relaciones.

**Comment by nmorandeira** [comment]
Agua: Esquema de un recipiente con agua y un bloque de hielo.
 Evaluación: el mapa conceptual presenta los conceptos y relaciones principales entre esos conceptos relacionados a las evaluaciones formativas. Una evaluación formativa es rápida e inequívoca de manera tal que es escalable. También tiene poder de diagnóstico para identificar vacíos y conceptos erróneos que pueden tener los/las estudiantes y que los/las docentes aclaran usando la retroalimentación que les dan las evaluaciones formativas. Esa retroalimentación también puede ser utilizada por los/las docentes para decidir si un tema se debe revisar, se puede saltear porque ya se conoce o se puede proceder porque se entendió.
 Modelos mentales: el mapa conceptual presenta los conceptos y relaciones principales entre esos conceptos relacionados a los modelos mentales. Los modelos mentales deben ser útiles y no necesitan ser completos o correctos. Cuando una persona novata (que puede tener una falsa confianza) desarrolla un modelo mental se convierte en un/una practicante competente.
Los mapas conceptuales se usan para representar un modelo mental por medio de nodos que representan conceptos y enlaces que representan relaciones. Las relaciones habilitan recordar los conceptos. Estos mapas también ayudan a diseñar una lección siguiendo las relaciones.
