### ISSUE TITLE
Alt-text for figure Appendix H

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#381]
- [x] El diagrama presenta una cuadrícula de tres por tres sin las lineas externas.  En el primer renglón tiene los números uno a tres, en el segundo cuatro a seis y en el tercero siete a nueve.  De esta manera el número uno está rodeado por una línea vertical a su derecha y una línea horizontal debajo.  El número dos está rodeado por dos lineas verticales (a su derecha y a su izquierda) y una línea horizontal en su parte inferior.  El número tres está rodeado por una línea vertical a su izquierda y una línea horizontal en su parte inferior.
Al número cuatro lo rodean dos líneas horizontales (arriba y abajo) y una línea vertical a su derecha.  El número cinco está dentro de un cuadrado con todas las líneas marcadas.  El número seis tiene las dos líneas horizontales (arriba y abajo) y una línea vertical a su izquierda.
El número siete tiene una línea horizontal arriba y otra linea vertical a la derecha.  El número ocho está rodeado por dos lienas verticales (una a cada lado) y una linea horizontal en la parte superior.  Finalmente el número nueve tiene una linea vertical a la izquierda y una linea horizontal arriba.

**Comment by nmorandeira** [comment]
El diagrama presenta una cuadrícula de tres por tres sin las líneas externas. En el primer renglón tiene los números uno a tres, en el segundo cuatro a seis y en el tercero siete a nueve. De esta manera el número uno está rodeado por una línea vertical a su derecha y una línea horizontal debajo. El número dos está rodeado por dos líneas verticales (a su derecha y a su izquierda) y una línea horizontal en su parte inferior. El número tres está rodeado por una línea vertical a su izquierda y una línea horizontal en su parte inferior.
Al número cuatro lo rodean dos líneas horizontales (arriba y abajo) y una línea vertical a su derecha. El número cinco está dentro de un cuadrado con todas las líneas marcadas. El número seis tiene las dos líneas horizontales (arriba y abajo) y una línea vertical a su izquierda.
El número siete tiene una línea horizontal arriba y otra linea vertical a la derecha. El número ocho está rodeado por dos líneas verticales (una a cada lado) y una línea horizontal en la parte superior. Finalmente, el número nueve tiene una línea vertical a la izquierda y una línea horizontal arriba.

**Comment by nmorandeira** [comment]
algunas tildes
