### ISSUE TITLE
Alt-text for figures in Appendix G

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#382]
- [x] Mapa conceptual desde el punto de vista de los socios de la biblioteca: los/as socios/as de la biblioteca llevan niños/as a talleres de cuentos que se realizan en el edificio de la biblioteca, el cual está lleno de libros y materiales.  Los/as socios/as también buscan libros y hacen preguntas al personal de la biblioteca.  Este personal se encarga de comprar libros y materiales, ayuda a los/as socios/as y evalúa si debe aplicar multas a algunos socios/as.
- [x] Mapa conceptual desde el punto de vista de la dirección de la biblioteca: el presupuesto de la bilbioteca es controlado por el gobierno de la ciudad.  Este presupuesto paga por el personal, las instalaciones, el material y los programas de la biblioteca.  Los/as socios/as usan los materiales, participan en los programas y visitan las instalaciones donde trabaja el personal.  Este personal es gobernado por los sindicatos que pueden influenciar al gobierno de la ciudad.
- [x] Mapa conceptual desde el punto de vista de los/as amigos/as de la biblioteca: Los/as amigos/as de la biblioteca realizan las ventas de libros que generan fondos.  Estos fondos se usan para pagar el mantenimiento y mejoras de las instalaciones y para pagar la realización de programas que apoyan a los socios/as y a la comunidad.  Algunos/as de estos/as socios/as  son parte d los/as amigos/as de la biblitoeca y también participan en las ventas de libros.  El personal de la biblioteca es consultado por los socios/as sobre las instalaciones y los programas disponibles en la biblioteca.

**Comment by nmorandeira** [comment]
Mapa conceptual desde el punto de vista de los/las socios/as de la biblioteca: los/as socios/as de la biblioteca llevan niños/as a talleres de cuentos que se realizan en el edificio de la biblioteca, el cual está lleno de libros y materiales. Los/as socios/as también buscan libros y hacen preguntas al personal de la biblioteca. Este personal se encarga de comprar libros y materiales, ayuda a los/las socios/as y evalúa si debe aplicar multas a algunos socios/as.
 
 Mapa conceptual desde el punto de vista de la dirección de la biblioteca: el presupuesto de la bilbioteca es controlado por el gobierno de la ciudad. Con este presupuesto se paga por el personal, las instalaciones, el material y los programas de la biblioteca. Los/las socios/as usan los materiales, participan en los programas y visitan las instalaciones donde trabaja el personal. Este personal es gobernado por los sindicatos que pueden influenciar al gobierno de la ciudad.

 Mapa conceptual desde el punto de vista de los/las amigos/as de la biblioteca: Los/las amigos/as de la biblioteca realizan las ventas de libros que generan fondos. Estos fondos se usan para pagar el mantenimiento y mejoras de las instalaciones y para pagar la realización de programas que apoyan a los socios/as y a la comunidad. Algunos/as de estos/as socios/as son parte de los/as amigos/as de la biblitoeca y también participan en las ventas de libros. El personal de la biblioteca es consultado por los socios/as sobre las instalaciones y los programas disponibles en la biblioteca.

**Comment by nmorandeira** [comment]
(algunas ediciones menores de los/las)
