### ISSUE TITLE
Add and update check list and templates

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#385]
- Registration Form
- Post-event questionnaire
- Exit ticket
- Course invitation email template
- Share doc template (google doc, slide deck)
- Feedback rubric

**Comment by gvwilson** [comment]
:+1:

**Comment by yabellini** [comment]
Una mejora adicionar más templates de ejemplos como anexos, y/o checklist de ejemplos que los lectores puedan usar.

**Comment by yabellini** [comment]
Agregados casi todos los recursos listados aqui.
