### ISSUE TITLE
Alt-text for figures in memory.tex

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#386]
- [x] Mapa conceptual para estaciones del año: Las estaciones del año están determinadas por la cantidad de luz del sol y resultan en variaciones estacionales de temperatura.  La cantidad de luz del sol está determinada por la duración del día (que es mas larga en verano y más corta en invierno) y la altura del sol sobre el horizonte (que es más alta en verano y más baja en invierno).  La duración del día está determinada por la posición en órbita con ligera desviación en la distancia tiene un efecto insignificante.  Esta posición en órbita el eje apunta hacia o lejos del sol.  La inclinación del eje en verano apunta hacia el sol.
- [x] Mapa conceptual para un bucle for: se presentan dos diagramas. El diagrama de la izquierda presenta una caja con el concepto "Variable del bucle" de la cual salen dos flechas, una apuntando a otra caja con el concepto "colección" y la otra a una tercera caja con la etiqueta "cuerpo del bucle".  Esta última caja tiene una flecha que apunta a la caja "colección".  El diagrama de la derecha repite el esquema de la izquierda pero las flechas tienen etiquetas.  La lectura del diagrama queda como: la variable del bucle toma cada elemento de la colección y cambia en el cuerpo del bucle que corre ua vez para cada elemento de la colección.
- [x] Usando mapas conceptuales en el diseño de la lección: la fotosíntesis produce: a) glucosa que guarda energía y b) oxígeno que es liberado al aire; para este proceso requiere CO2 (absorvido del aire), agua y luz.  La fotosíntesis ocurre en los cloroplastos que absorven luz.
- [x] Repreetnación no fragmentada: se presentan los número 1 a 9 al lado de una serie de lineas.  _Aqui copiar la descripción de la resolución porque el texto es casi el mismo_

**Comment by nmorandeira** [comment]
Mapa conceptual para estaciones del año: las estaciones del año están determinadas por la cantidad de luz del sol y resultan en variaciones estacionales de temperatura. La cantidad de luz del sol está determinada por la duración del día (que es mas larga en verano y más corta en invierno) y la altura del sol sobre el horizonte (que es más alta en verano y más baja en invierno). La duración del día está determinada por la posición en órbita con una ligera desviación, que en la distancia tiene un efecto insignificante. Por esta posición en órbita, el eje apunta hacia o lejos del sol. La inclinación del eje en verano apunta hacia el sol.
 
 Mapa conceptual para un bucle \emph{for}: se presentan dos diagramas. El diagrama de la izquierda presenta una caja con el concepto "Variable del bucle" de la cual salen dos flechas, una apuntando a otra caja con el concepto "colección" y la otra a una tercera caja con la etiqueta "cuerpo del bucle". Esta última caja tiene una flecha que apunta a la caja "colección". El diagrama de la derecha repite el esquema de la izquierda pero las flechas tienen etiquetas. La lectura del diagrama queda como: la variable del bucle toma cada elemento de la colección y cambia en el cuerpo del bucle que corre una vez para cada elemento de la colección.
 
 Usando mapas conceptuales en el diseño de la lección: la fotosíntesis produce: a) glucosa que guarda energía y b) oxígeno que es liberado al aire; para este proceso requiere CO2 (absorbido del aire), agua y luz. La fotosíntesis ocurre en los cloroplastos que absorben luz.
 
 Representación no fragmentada: se presentan los números 1 a 9 al lado de una serie de líneas. _**Aquí copiar la descripción de la resolución porque el texto es casi el mismo.**_

**Comment by nmorandeira** [comment]
ediciones menores de typos
