### ISSUE TITLE
Alt-text for figures in individual.tex

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#388]
- [x] Aprendizaje activo: el aprendizaje activo es mejor que el aprendizaje pasivo.  La práctica distribuida, de recuperación, intercalda, la elaboración, ejemplos concretos y la codificación dual ayudan a que el aprendizaje activo ocurra. Una persona novata no tiene conexiones, una persona competente tiene pocas conexiones y una persona experta tiene muchas.  El aprendizaje activo forma estas conexiones.

**Comment by nmorandeira** [comment]
Aprendizaje activo: el aprendizaje activo es mejor que el aprendizaje pasivo. La práctica distribuida, de recuperación, intercal**a**da, la elaboración, ejemplos concretos y la codificación dual ayudan a que el aprendizaje activo ocurra. Una persona novata no tiene conexiones, una persona competente tiene pocas conexiones y una persona experta tiene muchas. El aprendizaje activo forma estas conexiones.
