### ISSUE TITLE
Alt-text for figures in performance.tex

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#389]
- [x] Sentimientos sobre el feedback: caricatura con tres cuadros.  En el primero se muestra una persona sonriente y muy contenta recibiendo halagos (brillante, sos mi inspiración, sus una gran persona, me algrás el día, ten buen amigo/a, ¡qué genio/a!, ¡sos fantástico/a!) y un solo comentario que dice "A veces so un/a idiota".  En el segundo recuadro se ve a la persona cenando, aún con una pequeña sonrisa, recordando los comentarios: los buenos se van desvaneciendo, pero el comentario negativo está presente de una forma preponderante.  En el último recuadro, la persona está en la cama, acostada, con una xpresión de tristeza y el único comentario que recuerda es el negativo.
- [x] Rubrica de enseñanza: diagrama que presenta una plano con dos ejes, uno vertical y otro horizontal. El eje vertical tiene en la punta superior las palabras _salió bien_ y en la punta inferior las palabras _se puede mejorar_.  El eje horizontal tiene las palabras _presentación_ a la izquierda y _contenido_a la derecha.  En le cuadrante arriba a la izquierda se presentan los conceptos: voz clara, buen contacto visual.  En el cuadrante arriba a la derecha se presentan los conceptos _orden lógico_ y _ejemplo del mundo real_.  En el cuadrante abajo a la izquierda se presenta el concepto _habló demasiado rápido_, _jerga_ y _gestos con las manos_.  Finalmente, en el cuadrante debajo a la derecha aparece _no motivó la lección_.
- [x] Retroalimentación: para enseñar se debería usar programación en vivo, usar los errores y pedir predicciones.  Enseñar se puede entender como una actuación que obtiene y mantiene la atención.  La rúbrica guía la práctica que mejora con la enseñanza.  La enseñanza mejora con la devolución, al igual que la práctica y la misma rúbrica.

**Comment by nmorandeira** [comment]
Sentimientos sobre la retroalimentación: historieta con tres cuadros. En el primer cuadro, se muestra una persona sonriente y muy contenta recibiendo halagos ("¡Brillante", "¡Sos mi inspiración!", ¡Sos una gran persona!", "¡Me alegrás el día!", "¡Tan buen amigo/a!", "¡Qué genio/a!", "¡Sos fantástico/a!") y un solo comentario que dice "A veces sos un/a idiota". En el segundo cuadro, se ve a la persona cenando, aún con una pequeña sonrisa, recordando los comentarios: los buenos se van desvaneciendo, pero el comentario negativo está presente de una forma preponderante. En el último recuadro, la persona está en la cama, acostada, con una expresión de tristeza y el único comentario que recuerda es el negativo.

**Comment by nmorandeira** [comment]
Rúbrica de enseñanza: diagrama que presenta un plano con dos ejes cartesianos, uno vertical y otro horizontal. El eje vertical tiene en la punta superior las palabras "salió bien" y en la punta inferior las palabras "se puede mejorar". El eje horizontal tiene las palabras "presentación" a la izquierda y "contenido" a la derecha. En el cuadrante arriba a la izquierda se presentan los conceptos: "voz clara", "buen contacto visual". En el cuadrante arriba a la derecha se presentan los conceptos "orden lógico" y "ejemplo del mundo real". En el cuadrante abajo a la izquierda se presenta el concepto "habló demasiado rápido", "jerga" y "gestos con las manos". Finalmente, en el cuadrante debajo a la derecha aparece "no motivó la lección".

**Comment by nmorandeira** [comment]
del tercero no edito nada!

**Comment by nmorandeira** [comment]
Puse comillas para los términos, la alternativa es usar itálicas. No sé cómo se lee en screen-readers
