### ISSUE TITLE
Alt-text for Motivation and Demotivation

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#395]
- [x] ¿Qué enseñar?: Gráfico con el eje vertical representando "Utilidad una vez dominado el tema" con la escala 'bajo', 'medio' y 'alto' y el eje horizontal representando el 'Tiempo para dominar el tema' con la escala 'minutos', 'horas', 'días'.  Arriba a la izquierda que representa alta utilidad y poco tiempo (minutos) indica que enseña esto primero.  Al medio (utilidad medio y tiempo en horas) tienes que pensar en las ventajas de enseñar ese tema y abajo a la derecha (donde la utilidad es baja y el tiempo es de días) no te molestes en agregarlo a la lección.
- [x] Gráfico de estudiantes universitarias en ciencias de la computación en USA: el gráfico presenta el porcentaje de títulos de grado otorgado a mujeres en medicina, derecho, física y computación desde 1960 a 2015.  Las lineas correspondientes a medicina, derecho y física fueron aumentando sostenidamente con el paso de los años hasta llegar a valores entre el 40 y el 50%.  Mientras que los títulos de computacion tuviron su pico en la década del 80 superando apenas el 35% y luego una sostenida disminución hasta llegar al 17% en 2015.
- [x] Grafico de títulos otorgados y matricula femenina: en el eje "y" de la izquierda se muestra el porcentaje con una escala desde 0% a 35% y en el eje y de la derecha se muestra la cantidad de títulos otorgados con una escala desde 0 a 70.000.  En el eje horizontal se presentan los años desde 1975 a 2015.  La evolución de la cantidad de títulos presenta dos picos, uno en 1968 con más de 40.000 títulos otorgados y otro en 2006 con 60.000 títulos otorgados.  Llegando a 2015 también se ve un crecimiento en la cantidad de títulos cercana a los 60.000.  El porcentaje de títulos otorgados a mujeres tiene su pico en la década del 80 con un porcentaje superior al 35% y luego disminuye hasta llegar al 17% en 2015.  
- [x] Motivación: La motivación puede ser intrínseca (ayuda al aprendizaje) ó extrínsica (no ayuda al aprendizaje) y sucede tanto en clase como fuera de ella.  La motivación es ayudada por la inclusión que no debe usar un modelo deficitiario y es ayudada por buenos aliados y por un código de conducta.  La motivación es afectada negativamente por la indiferencia, la imprevisibilidad y la injusticia.  Por otro lado, la competencia, la autonomía y la relación contribuyen positivamente a la motivación.

**Comment by nmorandeira** [comment]
¿Qué enseñar?: Gráfico con dos ejes cartesianos, con el eje vertical se titula "Utilidad una vez dominado el tema" con la escala "baja", "media" y "alta" y el eje horizontal se titula "Tiempo para dominar el tema" con la escala "minutos", "horas", "días". Arriba a la izquierda, que representa alta utilidad y poco tiempo (minutos), se indica "enseña esto primero". Al medio (utilidad media y tiempo en horas), se indica que tienes que pensar en las ventajas de enseñar ese tema. Abajo a la derecha (donde la utilidad es baja y el tiempo es de días), se indica "no te molestes" en agregarlo a la lección.

**Comment by nmorandeira** [comment]
Gráfico de estudiantes universitarias en ciencias de la computación en Estados Unidos: el gráfico presenta el porcentaje de títulos de grado otorgado a mujeres en Medicina, Derecho, Ciencias Físicas y Ciencias de la Computación de 1960 a 2015. Las lineas correspondientes a Medicina, Derecho y Ciencias Físicas fueron aumentando sostenidamente con el paso de los años hasta llegar a valores de entre 40 y 50%. Los títulos de computación tuvieron su pico en la década del 80 superando apenas el 35% y luego una sostenida disminución hasta llegar al 17% en 2015.

**Comment by nmorandeira** [comment]
Grafico de títulos otorgados y matricula femenina en Ciencias de la Computación: en el eje "y" de la izquierda se muestra el porcentaje con una escala desde 0% a 35% y en el eje "y" de la derecha se muestra la cantidad de títulos otorgados con una escala desde 0 a 70.000. En el eje horizontal se presentan los años desde 1975 a 2015. La evolución de la cantidad de títulos presenta dos picos, uno en 1968 con más de 40.000 títulos otorgados y otro en 2006 con 60.000 títulos otorgados. Llegando a 2015 también se ve un crecimiento en la cantidad de títulos cercana a los 60.000. El porcentaje de títulos otorgados a mujeres tiene su pico en la década del 80 con un porcentaje superior al 35% y luego disminuye hasta llegar al 17% en 2015.

**Comment by nmorandeira** [comment]
Motivación (mapa conceptual): La motivación puede ser intrínseca (ayuda al aprendizaje) ó extrínseca (no ayuda al aprendizaje) y sucede tanto en clase como fuera de ella. La motivación es ayudada por la inclusión que no debe usar un modelo deficitiario y es ayudada por buenos aliados y por un código de conducta. La motivación es afectada negativamente por la indiferencia, la imprevisibilidad y la injusticia. Por otro lado, la competencia, la autonomía y la relación contribuyen positivamente a la motivación.
