### ISSUE TITLE
alt-text figures Arquitectura cognitiva

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#396]
- [x] Arquitectura cognitiva: esquema que presenta un recuadro que dentro contiene un modelo mental de cajas y flechas relacionandosé representando a la memoria de largo plazo.  Un segundo recuadro representa a la memoría de corto plazo.  Dentro tiene una caja representando al canal visual y otra caja representando al canal verbal.  Desde ambas cajas salen una flecha hacia un signo más desde el cual sale una relación llamada codificar hacia la memoría de largo plazo.  Desde la memoria de largo plazo sale una relación llamada recuperar hacia la memoria de corto plazo.  Las imagenes tomadas a partir de los ojos y el habla registrada por medio de los oídos se relacionan con los canales visuales y verbales de la memoría a corto plazo respectivamente.
- [x] Construyendo una oración: el esquema presenta dos renglones con palabras en catalán en cajas y con diferentes fuentes de letras, tamaños y estilos (algunas con negrita, algunas con cursivas).  En el primer renglón se presentan las siguientes palabras en este orden: com, el, teu, está, avui, genoll. En el segundo renglón se acomodan las palabras en el orden correspondiente para generar una frase correcta: com, está, el, teu, genoll, avui.
- [x] Carga cognitiva: el pensamiento está limitado por la carga cognitiva.  Esta carga cognitiva puede ser intrísica (que es deseable), pertinente (que debería ser reducida) y extrínseca (que debería ser eliminada).  El pensamiento accede a la memoria de corto plazo, el cual codificado pasa a la memoria de largo plazo desde la cual se puede recuperar a la memoría de corto plazo para ser utilizado. El discurso usa el canal lingüístico, las imágenes usan el canal visual y el texto usa ambos canales.  El canal visual puede reforzar o puede conflictuar el canal lingüístico.  Estos canales integrados se almacenan en la memoria de corto plazo.

**Comment by nmorandeira** [comment]
Arquitectura cognitiva: esquema que presenta dos recuadros principales, uno llamado "memoria de largo plazo" y otro "memoria de corto plazo". El recuadro "memoria de largo plazo" contiene un modelo mental de cajas y flechas que se relacionan entre sí. En el recuadro "memoria de corto plazo", hay una caja representando al canal visual y otra caja representando al canal verbal. Desde ambas cajas salen una flecha hacia un signo más desde el cual sale una relación llamada "codificar" hacia la memoria de largo plazo. Desde la memoria de largo plazo sale una relación llamada "recuperar" hacia la memoria de corto plazo. Las imágenes tomadas a partir de los ojos y el habla registrada por medio de los oídos están por fuera de los dos recuadros principales y se relacionan con los canales visuales y verbales de la memoria a corto plazo, respectivamente.

**Comment by nmorandeira** [comment]
Construyendo una oración: el esquema se titula "¿Cómo está tu rodilla hoy?" y presenta dos renglones con palabras en catalán en cajas y con diferentes fuentes de letras, tamaños y estilos (algunas con negrita, algunas con cursivas). En el primer renglón se presentan las siguientes palabras en este orden: "com", "el", "teu", "està", "avui", "genoll". En el segundo renglón se acomodan las palabras en el orden correspondiente para generar una frase correcta: "com", "està", "el", "teu", "genoll", "avui".
