### ISSUE TITLE
alt-text for on-line teaching

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#398]
- [x] Patrones para grabaciones en pantalla: Prepararte para iniciar una grabación en pantalla y ensayar el guión.  Decidir en que parte de la pantalla hacer foco, una vez que tenemos la vista enfocada y muestramos las interacciones del mouse y del teclado, para mantener a los/las espectadores enfocadas/os usar enfoque estrecho y luego combinar las difrentes grabaciones de pantallas en multiples pasadas.  Al finalizar podemos agregar un paquete de recursos adicionales, agregar efectos viusales que lo ameriten, contenido estático (como diapositivas de imágenes) y publicidad de recursos que resulta en el embellecimiento de nuestro video.  Otra perte del ensayo del guión corresponde a insertar texto sin errores y dando tiempo a leer (se conoce como narración silenciosa).  La grabación de la pantalla se debe hacer a paso lento y sin grabar el audio para aprovechar una narración silenciosa; en la cual debemos mostrar las entradas de teclado.  Lugo de hacer una grabación de pantalla breve (ya sabemos, lo corto y bueno, doblemente bueno) se puede empaquetar en pistas de capítulo, estas pistas contendrán acciones importantes identificadas en multiples pasadas de la grabacion en pantalla.

**Comment by nmorandeira** [comment]
Patrones para grabaciones en pantalla (mapa conceptual): Prepararte para iniciar una grabación en pantalla y ensayar el guión. Decidir en qué parte de la pantalla hacer foco, una vez que tenemos la vista enfocada y probamos las interacciones del mouse y del teclado, para mantener a los/las espectadores enfocadas/os usar enfoque estrecho y luego combinar las diferentes grabaciones de pantallas en múltiples pasadas. Al finalizar podemos agregar un paquete de recursos adicionales, agregar efectos viusales que lo ameriten, contenido estático (como diapositivas de imágenes) y publicidad de recursos que resulta en el embellecimiento de nuestro video. Otra parte del ensayo del guión corresponde a insertar texto sin errores y dando tiempo a leer (se conoce como narración silenciosa). La grabación de la pantalla se debe hacer a paso lento y sin grabar el audio para aprovechar una narración silenciosa; en la cual debemos mostrar las entradas de teclado. Luego de hacer una grabación de pantalla breve (ya sabemos, lo corto y bueno, doblemente bueno) se puede empaquetar en pistas de capítulo, estas pistas contendrán acciones importantes identificadas en multiples pasadas de la grabacion en pantalla.

**Comment by nmorandeira** [comment]
@yabellini en la figura, me parece que en lugar de "mostrar" (interacciones del mouse) es "probar", puede ser?

**Comment by nmorandeira** [comment]
@yabellini aclaré "mapa conceptual" entre paréntesis, luego del título del gráfico. Ver en los anteriores que ya están mergeados: en algunos creo que no está aclarado, en otros es el título (ej Mapa conceptual de los patrones ....)

**Comment by yabellini** [comment]
Puede ser lo de la figura, creo que lo miré desde el papel y no desde la web.  Ahora chequeo!
