### ISSUE TITLE
alt-text tipos de ejercicios

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#399]
- [x] Etiquetado de diagramas: inicia con una caja con una letra P mayúscula, salen cuatro flechas, dos hacia dos cajas diferentes con la misma etiqueta: "texto", otra hacia una caja con la letra I mayúscula y la última hacia una caja con la letra B mayúscula.  Desde la caja de la letra B salen dos flechas, una hacia una caja etiquetada como "texto" y otra hacia una caja con la letra U mayúscula.  Desde las letras I e U también salen flechas hacia diferentes cajas etiquetadas como "texto".
- [x] Unir los ítems: en el primer renglón llamado "Operador", se presetan cajas con símbolos en el siguiente orden: signo de pregunta, asterisco, más, peso, potencia.  En el segundo renglón llamado "Acción" hay cajas etiquetadas con el siguiente orden: inicio de línea, cero o uno, fin de línea, uno o más, cero o más.

**Comment by nmorandeira** [comment]
Etiquetado de diagramas: inicia con una caja con una letra P mayúscula, salen cuatro flechas, dos hacia dos cajas diferentes con la misma etiqueta: "texto", otra hacia una caja con la letra I mayúscula y la última hacia una caja con la letra B mayúscula. Desde la caja de la letra B salen dos flechas, una hacia una caja etiquetada como "texto" y otra hacia una caja con la letra U mayúscula. Desde las letras I e U también salen flechas hacia diferentes cajas etiquetadas como "texto".
 Unir los ítems: en el primer renglón llamado "Operador", se presentan cajas con símbolos en el siguiente orden: signo de pregunta, asterisco, más, peso, potencia. En el segundo renglón llamado "Acción" hay cajas etiquetadas con el siguiente orden: inicio de línea, cero o uno, fin de línea, uno o más, cero o más.
