### ISSUE TITLE
alt-text In the Classroom

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#401]
- [x] El efecto Dunning-Kruger: el gráfico muestra una escala de 0 a 100 en el eje vertical y en el eje horizontal Las etiquetas: Primer cuartil, segundo cuartil, tercer cuartil y cuarto cuartil en ese orden.  Hay tres series graficadas, la correspondiente a la "habilidad percibida" en el primer cuartil toma valores entre 50 y 60 que son muy similares a los presentes en el segundo cuartil.  El tercer cuartil presenta valores por encima de 60 y el cuarto cuartil valores cercanos a 80.  La serie "puntaje recibido en la prueba", copia de forma casi idéntica la serie "habilidad percibida".  La serie "puntuación real de la prueba" toma valores cercanos a 10 en el primer cuartil, valores cercanos a 30 en el segundo cuartil, cercanos a 60 en el tercer cuartil y entre 80 y 90 para el cuarto cuartil.

**Comment by nmorandeira** [comment]
El efecto Dunning-Kruger: el gráfico muestra una escala de 0 a 100 en el eje vertical y en el eje horizontal las etiquetas: "Primer cuartil", "Segundo cuartil", "Tercer cuartil" y "Cuarto cuartil", en ese orden. Hay tres series graficadas, la correspondiente a la "habilidad percibida" en el primer cuartil toma valores entre 50 y 60 que son muy similares a los presentes en el segundo cuartil. El tercer cuartil presenta valores por encima de 60 y el cuarto cuartil valores cercanos a 80. La serie "puntaje recibido en la prueba", copia de forma casi idéntica la serie "habilidad percibida". La serie "puntuación real de la prueba" toma valores cercanos a 10 en el primer cuartil, valores cercanos a 30 en el segundo cuartil, cercanos a 60 en el tercer cuartil y entre 80 y 90 para el cuarto cuartil.
