### ISSUE TITLE
alt-text para A Lesson Design Process

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#402]
- [x] Los/as estudiantes difieren de los docentes y se describen como estudiantes (o personas) tipo que tienen antecedentes generales, punto de partida, consideraciones especiales y necesidades percibidas.  Los docentes crean lecciones que ayudan a un subgrupo de estudiantes. Estas lecciones solucionan necesiddes reales que pueden diferir de las necesidades percibidas aunque se describen en términos de necesidades percibidas.

**Comment by nmorandeira** [comment]
Personas tipo (mapa conceptual): Los/las estudiantes difieren de los/las docentes y se describen como estudiantes (o personas) tipo que tienen antecedentes generales, punto de partida, consideraciones especiales y necesidades percibidas. Los/las docentes crean lecciones que ayudan a un subgrupo de estudiantes. Estas lecciones solucionan necesidades reales que pueden diferir de las necesidades percibidas, aunque se describen en términos de necesidades percibidas.

**Comment by nmorandeira** [comment]
ediciones menores y le agregué título de gráfico y (mapa conceptual), estaría bueno que qqueden todos en el mismo estilo
