### ISSUE TITLE
alt-text para Pedagogical Content Knowledge

### ISSUE THREAD

**Issue by yabellini** [gvwilson/teachtogether.tech#406]
- [x] Trayectoria de aprendizaje para condiciones: este diagrama presenta una serie de conceptos relacionados y marca con diferentes tipos de trama en las lineas de los conceptos las trayectorias para enseñarlos.  Trayectoria inicial: A menudo las acciones resultan de causas específicas,  Una condición es algo que puede ser verdadero o falso y Un condicional conecta una condición a un resultado, Cada estado de una condición puede tener su propia acción y Declaraciones condicionales evalúan condiciones y ejecutan acciones.  Trayectoria intermedia: Declaraciones condicionales pueden crear bifurcaciones en el flujo de ejecución, Las computadoras requieren que se especifiquen todas las acciones, Algunas veces se deben considerar múltiples condiciones, Las condiciones pueden superponerse y se puede aplicar más de una.  Trayectoria avanzada: Una variable booleana puede ser verdadera o falsa, Los operadores lógicos se pueden utilizar para combinar condiciones, Las declaraciones condicionales se pueden combinar de varias maneras.
- [x] Scratch: captura de pantalla del lenguaje de programación por bloques Scratch
- [x] Efectividad de las intervenciones: El eje vertical presenta 10 categorías y el eje horizontal una escala de 0 a 50.  Las categorías Colaboración, cambio de contenido y apoyo de pares presentan valores de 35. "Contextualización" es igual a 40, CS0 toma el valor 43, Tema del juego: 17 Sistema de clasificación: 28, Trabajo en equipo: 45, Medios de computación 48 y Otro apoyo 32.

**Comment by nmorandeira** [comment]
Trayectoria de aprendizaje para condiciones: este diagrama presenta una serie de conceptos relacionados y marca con diferentes tipos de trama las trayectorias (inicial, intermedia, avanzada) para enseñarlos. Trayectoria inicial: "A menudo las acciones resultan de causas específicas", "Una condición es algo que puede ser verdadero o falso" y "Un condicional conecta una condición a un resultado", "Cada estado de una condición puede tener su propia acción" y "Declaraciones condicionales evalúan condiciones y ejecutan acciones". Trayectoria intermedia: "Declaraciones condicionales pueden crear bifurcaciones en el flujo de ejecución", "Las computadoras requieren que se especifiquen todas las acciones", "Algunas veces se deben considerar múltiples condiciones", "Las condiciones pueden superponerse y se puede aplicar más de una". Trayectoria avanzada: "Una variable booleana puede ser verdadera o falsa", "Los operadores lógicos se pueden utilizar para combinar condiciones", "Las declaraciones condicionales se pueden combinar de varias maneras".

**Comment by nmorandeira** [comment]
Scratch: captura de pantalla del lenguaje de programación por bloques Scratch.

**Comment by nmorandeira** [comment]
Efectividad de las intervenciones (gráfico de barras horizontales): El eje vertical presenta 10 categorías y el eje horizontal una escala de 0 a 50 de efectividad de las intervenciones. Las categorías "Colaboración", "Cambio de contenido" y "Apoyo de pares presentan valores" de 35. "Contextualización" es igual a 40, "CS0" toma el valor 43, "Tema del juego": 17, "Sistema de clasificación": 28, "Trabajo en equipo": 45, "Medios de computación" 48 y "Otro apoyo" 32.
