### ISSUE TITLE
Introducción Español

### ISSUE THREAD

**Issue by ernestomirt** [gvwilson/teachtogether.tech#436]
En la parte que se llama **Quién Eres,** cuando hablan de Emilia, dice que ella "... Se encuentra está reclutando", podría ser:

 "Se encuentra reclutando", sin el "está", o "Está reclutando", sin el "Se encuentra".

Más adelante, en la misma sección de Quien eres, cuando describe a René dice:

"cada vez se convence más de que tiene", podría ser  
"cada vez se convence más que tiene"

Más adelante, en la misma Introducción, en la sección denominada **"Qué otras cosas leer"**:
        Donde dice 
        "... el cual explica qué cosas son ciertas sobre la educación al explicar qué cosas ... ", quizás usar "quien" y sustituir el primer explica por plantea para evitar la cacofonía o redundancia. Por ejemplo:

        "quién plantea qué cosas son ciertas sobre la educación al explicar qué cosas... "

**Comment by nmorandeira** [comment]
Hola! @ernestomirt  Muchas gracias!!
Incorporé todos tus cambios excepto uno que detallo acá abajo. Aún no los verás en la versión online porque @yabellini debe compilar el html, pero ya aparecerán.

**Convencer _de_ que** Omitir el "de" es un [queísmo ](https://www.rae.es/dpd/que%C3%ADsmo). Sucede que tenemos mucha costumbre de tratar de evitar los dequeísmos (usar "de que" cuando debería ser sólo "que") que a veces cometemos queísmos. Aquí justo en el ejemplo del link usan el verbo _convencer_. 
_b) Con verbos no pronominales que se construyen con un complemento de régimen: convencer de algo, insistir en algo, tratar de algo (en el sentido de ‘procurarlo, intentarlo’), etc.: Lo convencí de que escribiera el artículo (no Lo convencí que escribiera el artículo); Insistió en que nos quedáramos a cenar (no Insistió que nos quedáramos a cenar); Trato de que estéis a gusto (no Trato que estéis a gusto)._
