### ISSUE TITLE
Capítulo Modelos mentales y evaluación formativa. [Español]

### ISSUE THREAD

**Issue by ernestomirt** [gvwilson/teachtogether.tech#437]
- Separar con coma ","  Natalia Morandeira de Ruth Chirinos en las autoras de la traducción
- Luego del Resumen en la frase:
    - " ... más que si alguien sabe o no algunos hechos específicos.", el "que" parece está demás, debería ser:
    -  "... más si alguien sabe o no algunos hechos específicos."

- En el ejemplo de la máquina nocional, punto 12., dice:
    - "Cuando la función finaliza, Python la borra del marco del de pila ", debería decir:
    - Cuando la función finaliza, Python la borra del marco de la pila 

- En Síntomas de ser  una persona novata, el link de la nota está pegado a un palabra anterior:
    - "La gente que hace esto generalmente dice cosas queni siquiera son falsas.", se debe separar en
    -  "queni siquiera son falsas"
- En Modelar modelos mentales de las personas  novatas, dónde dice:
    - "(i.e. qué concepto erróneo pretende ser identificada con cada distractor)", debería ser:
    - "IDENTIFICADO con cada distractor"

**Comment by nmorandeira** [comment]
Muchas gracias por la revisión @ernestomirt !!
 - Separar con coma las autorías en la traducción: es algo que hay que corregir en general, por ahora no lo pudimos resolver @yabellini 
 - El resto de tus revisiones: incorporadas! 
 Además cambié "i.e." por "es decir". 
 No se verán los cambios en la versión online hasta que @yabellini no compile el html nuevamente
 Abrazo, Ernesto!
