### ISSUE TITLE
Agregar mención a Ernesto y compilar html

### ISSUE THREAD

**Issue by nmorandeira** [gvwilson/teachtogether.tech#439]
Agregar mención a Ernesto Mirt por sus revisiones en Intro.tex y Models.tex (no sé bien donde va) y compilar html

**Comment by nmorandeira** [comment]
Esperar a que Ernesto termine de leer porque está haciendo un issue por capítulo :smile:

**Comment by yabellini** [comment]
Hola Nati! Sí consultó x mail como contribuir y acordamos un issue por capítulo. Yo me tomé el finde y recién veo esto. Mil gracias por ocuparte de aplicar sus sugerencias y explicar la razón cuando no.

**Comment by yabellini** [comment]
Cuando termine yo me encargo de agregarlo a colaboradores. 😊

**Comment by nmorandeira** [comment]
me asigno los otros issues también!

**Comment by ernestomirt** [comment]
> me asigno los otros issues también!

Hola Natalia, no sabía que te había asignado a ti. (No sabía que podía asignar a alguien) :-( 

Y estuve buscando la manera de poner ese label de Español con el color púrpura pero no logré hacerlo...! 

Bueno hoy subí varios capítulos en un sólo issues. Y creo que ya debo terminar mañana, en dado caso, cuando ya vaya la última, les coloco en el título del issue...!

Saludos

**Comment by nmorandeira** [comment]
No, me auto-asigné. Simplemente le estaba avisando a Yani! No te preocupes por las etiquetas, quizás tenés que tener permiso. Gracias por contribuir!

**Comment by yabellini** [comment]
Mención agregada, cuando tengamos todos los cambios listos compilamos HTML y re agrego alt-texts. :-P

**Comment by yabellini** [comment]
Todos los cambios agregados, el HTML generado y los alt-text agregados.
