### ISSUE TITLE
Capítulo Arquitectura Cognitiva (español)

### ISSUE THREAD

**Issue by ernestomirt** [gvwilson/teachtogether.tech#441]
- Al final de la subsección **Ejemplos Desvanecidos** dice:
    - "También anima a que los/las estudiantes piensen en las similitudes y diferencias entre varios enfoques, lo que ayuda a crear los vínculos en sus modelos mentales y desde modo facilita la recuperación de la información.". El término "desde", luego de modelos mentales debe ser una equivocación, debería ser "y  **de ese** modo...", quedaría:
    - "También anima a que los/las estudiantes piensen en las similitudes y diferencias entre varios enfoques, lo que ayuda a crear los vínculos en sus modelos mentales y de ese modo facilita la recuperación de la información."

- Al final de Manuales Mínimos hay un punto "." entre la cita de  [Lazo1993] y [Carr2014], entendería por el contexto que el punto "." debería ir antes de [Lazo1993], quedaría:
    - "Estudios posteriores confirmaron que este enfoque superó al enfoque tradicional independientemente de la experiencia previa con computadoras. [Lazo1993] [Carr2014] resumieron este trabajo diciendo:"

- Otros modelos de aprendizaje, cuando hacen referencia a: 
    - "El sitio web de Learning Theories, teorías de aprendizaje en inglés y", creo que está invertido la referencia al idioma, debería ser:
    - El sitio web de Teorías de Aprendizaje, Learning Theories  en inglés y"

- En el mismo párrafo, un poco más adelante, luego del "conectivismo" hay un punto"." seguido de un paréntesis "(", ese punto parece estar de más. Debería ser:
    - "y el conectivismo (que sostiene que el conocimiento se distribuye, que el aprendizaje es el proceso de navegar, crecer y podar conexiones, y que enfatiza los aspectos sociales del aprendizaje que internet hace posible). "

**Comment by yabellini** [comment]
@nmorandeira como tengo tiempo empiezo a pasar estos issues asi voy limpiando el listado.

Todos los cambios aceptados con excepción del punto entre las citas.  La cita de Lazo es referencia de esa oración y la oración siguiente hace referencia al otro trabajo que no es cita de la oración previa.

Gracias @ernestomirt !
