### ISSUE TITLE
Capítulo Un proceso para diseñar lecciones (Español)

### ISSUE THREAD

**Issue by ernestomirt** [gvwilson/teachtogether.tech#443]
- Luego de la primera numeración dice:
    - "Este método de programación funciona porque escribir pruebas obliga a tenér ...", la tilde en "tenér" está demás. Debería ser:
    - "Este método de programación funciona porque escribir pruebas obliga a tener ..."
- Justo antes de Personas Tipos dice:
    - "Sin embargo, las notas que elaboremos deben presentar las tareas desarrolladas en el orden descripto anteriormente,...". Me parece que el uso de la grafía  "descripto" está en desuso en la mayoría de los países hispanos, lo sustituye "descrito"

- En Objetivos de aprendizaje, en la primera línea dice:
    - "los/los docentes a descubrir...", se repite "los", debería ser:
    - "los/las docentes a descubrir... "

- En Ejercicios /Crear personas tipos, se utiliza  "descripta". Si bien es una grafía permitida, no es de uso común en LA.
- En Ejercicios / Un patrón: problema, ejemplo, teoría y elaboración, en la frase final hay dos detalles. Uno es el punto y seguido dentro del paréntesis del acrónimo PETE. Lo otro es que, luego de enseñado hay un punto que no debería estar. Dice:
    - "PETE: Problem, Example, Theory, Elaborate.)  Elige algo que ya hayas enseñado o les hayan enseñado. y delinea una pequeña lección que siga estos cuatro pasos." y debería ser:
    - "PETE: Problem, Example, Theory, Elaborate).  Elige algo que ya hayas enseñado o les hayan enseñado y delinea una pequeña lección que siga estos cuatro pasos."

**Comment by yabellini** [comment]
Con respecto de descripto/a y descrito....no estoy preparada aún para escribirlo son la p.  Pero tomo el comentario.  Lo chequeo con el equipo de traducción.  Si es algo muy río platense nomás, lo cambiamos.

Con respecto del Punto y paréntesis, este es el acuerdo que hicimos:
* Si hay una oración completa dentro del paréntesis, el punto va adentro. (Por ejemplo si acá sigue un comentario extra sobre algo que decidió poner en una oración aparte, creo que lo hace con acotaciones.)
* Si el paréntesis es una aclaración dentro de la oración, el punto va afuera (este caso).

Entiendo que aplicaría la primera regla y por eso no lo cambié.  De nuevo gracias por esta lectura detallada.
