### ISSUE TITLE
Capítulo Conocimiento de la pedagogía del contenido (Español)

### ISSUE THREAD

**Issue by ernestomirt** [gvwilson/teachtogether.tech#444]
- En las primeras líneas que comienzan con hipervínculos, las comas "," siguientes están separadas de la palabra que le antecede. Quizás es por los hipervínculos?

- En Jerga, en la última línea, el paréntesis "(" que abre el nombre de ACM, está separado de la "A". Dice:
    - "( Association for Computing Machinery, por sus siglas en inglés).". Debería decir:
    - "(Association for Computing Machinery, por sus siglas en inglés)."

- En ¿Qué conceptos erroneos tienen las personas novatas? cuando se habla de los cuarenta errores que las docentes también pueden aclarar, luego del punto y seguido, dice:
    - "Una es la creencia de que las variables en los programas funcionan de la misma manera que en planillas de cálculo, es decir, que luego de ejecutar...", realmente debería ser "Uno", porque se está hablando de  "conceptos erróneos". Quedaría:
    - "Uno es la creencia de que las variables en los programas funcionan de la misma manera que en planillas de cálculo, es decir, que luego de ejecutar:"

- En ¿Cómo identifican y resuelven errores las personas novatas?
    - Primero hay dos signos de interrogación de cierre en el subtítulo
    - Más adelante, cuando dice:
        - "Aquellas personas que usaron un depurador de errores simbólico para recorrer sus programas, rastrearon su ejecución manualmente, escribieron pruebas y releyeron las especificaciones frecuentemente, todos hábitos que se pueden enseñar." La idea no se concretó, qué pasa con esas personas? o quiénes son esas personas?. Creo que la omisión viene desde el texto original en inglés y quizás se puede solucionar haciendo explícito un final de la frase que haga mención a las personas que son mejores programando. Por ejemplo:
        - "Aquellas personas que usaron un depurador de errores simbólico para recorrer sus programas, rastrearon su ejecución manualmente, escribieron pruebas y releyeron las especificaciones frecuentemente, todos hábitos que se pueden enseñar, __son mejores programando__." 

- En ¿Qué pasa con las pruebas (tests)?
    - En el segundo párrafo dónde dice:
        - "Los autores encontraron que los tests de las personas novatas usualmente tienen un bajo alcance (es decir, no testean gran parte del código) y que usualmente testean muchas cosas al mismo tiempo, lo que dificulta determicar las causas de los errores." Debería ser __determinar__ y no __determicar__. Quedaría:
        - Los autores encontraron que los tests de las personas novatas usualmente tienen un bajo alcance (es decir, no testean gran parte del código) y que usualmente testean muchas cosas al mismo tiempo, lo que dificulta determinar las causas de los errores."

- En ¿Importa el lenguaje?
    - Dónde dice:
        - "Nuestra sexta recomendación es preséntales interfaces basadas bloques a niñas/os y adolescentes...", debería ser:
        - "Nuestra sexta recomendación es preséntales interfaces basadas __en__ bloques a niñas/os y adolescentes..."
    - En Ejercicios:
        - Al final, en la frase:
            - "Haz que cada persona de la clase, independientemente, le otorgue un punto a las las ocho preguntas que más les interese... ", se repite "las" ante de ocho. Debería ser:
            - "Haz que cada persona de la clase, independientemente, le otorgue un punto a las ocho preguntas que más les interese... "

**Comment by yabellini** [comment]
Todo pasado, veremos si el doble sigo desaparece porque no está en el texto del LaTeX. 
Muchas gracias de nuevo Ernesto!!
