### ISSUE TITLE
Varios capitulos Parte II (Español)

### ISSUE THREAD

**Issue by ernestomirt** [gvwilson/teachtogether.tech#447]
Capítulo Tipos de Ejercicios:
 - Luego del cuadro de Invirtiendo programar y ejecutar, hay un párrafo que comienza con un paréntesis "(" que no se cierra, dede ser un error de transcripción:
    - "(En la práctica, la mayoría de los ejercicios programar y ejecutar son en realidad del tipo completar los espacios en blanco, porque el/la docente proporciona comentarios para recordarles a sus estudiantes los pasos que deben seguir. Las preguntas de este tipo son las bases para ejemplos desvanecidos...". Quedaría:
    - "En la práctica, la mayoría de los ejercicios programar y ejecutar son en realidad del tipo completar los espacios en blanco, porque el/la docente proporciona comentarios para recordarles a sus estudiantes los pasos que deben seguir. Las preguntas de este tipo son las bases para ejemplos desvanecidos..."

- En el cuadro de Ajuste mínimo, la primera línea de código dice:
    - "def inside(punto, mas_abajo, mas_alto):", me parece que la segunda variable es "mas_bajo" sin la "a". Quedaría:
    - "def inside(punto, mas_bajo, mas_alto):"

---
Capítulo Construyendo una comunidad de práctica:
- En Finlandia por qué no. No está el hipevínculo hacia el texto de Anu Partanen
- En Aprende luego hazlo, en el pirmer párrafo cuando están citando a RLadies y PyLadies hay unos  problemas con los paréntesis"()":
    - "... hasta las que son parte de las organizaciones globales como los capítulos de R-Ladies (Mujeres de R en inglés y PyLadies (Mujeres de Python en inglés. Luego de "(Mujeres de R en inglés" debería cerrarse el paréntesis, e igual luego de "Mujeres de Python en inglés"...". Qudaría así:
    - "hasta las que son parte de las organizaciones globales como los capítulos de R-Ladies (Mujeres de R en inglés) y PyLadies (Mujeres de Python en inglés)"
- En Empieza pequeño, hay una frase que no se entiende muy bien, y que parece un error de transcripción (¿Quizás un comando que no se interpretó bien: __/emph__) Dónde dice:
    - "Esto se basa en el efecto Ben Franklin: quien ya le ha hecho un favor a alguien es más propensa/o a hacerle /emphotro favor a la misma persona, (en comparación con la disposisión que tiene quien ha /emphrecibido un favor)." Debería ser:
    - "Esto se basa en el efecto Ben Franklin: quien ya le ha hecho un favor a alguien es más propensa/o a hacerle otro favor a la misma persona, (en comparación con la disposisión que tiene quien ha recibido un favor)."

- Luego de eso, en la primera negrillas, hay un punto "." seguido de una minúscula.
    - "Pide a las personas ser explícitas sobre su partida.  para que el resto sepa que realmente se han ido." Dos opciones, o se elimina el punto y se queda en minúscula o se coloca la "P" mayúscula. Me quedo con la primera:
    - "Pide a las personas ser explícitas sobre su partida para que el resto sepa que realmente se han ido. "

- Más adelante, en el siguiente grupo de de negrillas, hay una coma "," separada de la palabra que le antecede. En:
    - "Comparte los recursos esenciales del proyecto con las personas recién llegadas , tal como las normas y pautas para contribuir." Debería ser:
    - "Comparte los recursos esenciales del proyecto con las personas recién llegadas, tal como las normas y pautas para contribuir."

- En el siguiente grupo de negrillas, se escapo una tílde en "Pregunta". Dónde dice:
    - "Pregunta a las personas qué quieren en vez de adivinar. Así como no eres tus estudiantes (Sección 6.1), probablemente seas diferente a otras personas de tu organización. __Pregúnta__...". Debería ser:
    - "Pregunta a las personas qué quieren en vez de adivinar. Así como no eres tus estudiantes (Sección 6.1), probablemente seas diferente a otras personas de tu organización. Pregunta...

- En el mismo párrafo, hay un punto "." seguido de una minúscula que  quizáspueda  ser una coma ",":
    - "Pueden decir: “Cualquier cosa”. pero ...". Podría ser:
    - Pueden decir: “Cualquier cosa”, pero... "
- En Cuidarte y cuidar a tu comunidad, aparece nuevamente el __emph__ esta vez sin el __/__. Justo en el paréntesis que habla del "burnout en inglés".
- En los Ejercicios, cuando hacen referencia a Personas que puede conocer, Cristian comete un error pues su frase inicia con comilla simple ' y no con comilla doble ", aunque su frase cierra con comilla doble. Era de esperarse de Cristian jejejeje. Está así:
    - ‘Todas las partes han cometido errores,". Debería ser:
    - "Todas las partes han cometido errores,"
- En Contrataciones, la pregunta 1, tiene dos "o" seguidas:
    - "¿Tienes personal asalariado en tu organización __o o__ son todas/os voluntarias/os?"

**Comment by yabellini** [comment]
He realizado todos los cambios que sugeriste.  Había errores en el LateX donde aparecia el emph.
