### ISSUE TITLE
Varios Capítulos Parte III y última (español)

### ISSUE THREAD

**Issue by ernestomirt** [gvwilson/teachtogether.tech#448]
Capítulo Difusión y vinculación

- En Marketing, la segunda viñeta trata de usar lenguaje inclusivo de génerp, pero es innecesario:
    - "los/las personas", en este caso es 
    - "__las__ personas"
- Más adelante hay dos puntos ":" que están mal ubicados. Donde dice:
    - "En el ejemplo del taller de fin de semana, podríamos usar este tono para los/las participantes" 
- En Marcas y posicionamiento, hay una mayúscula luego de un punto y coma ";"
    - "Una marca es la primera reacción de una persona a la mención de un producto; Si la reacción es". Debería ser:
    - "Una marca es la primera reacción de una persona a la mención de un producto; si la reacción es"
- Despúes del cuadro de Mitos fundacionales, hay una palabramal escrita:
    - "Con esa inforamción puedes leer". Debería ser:
    - "Con esa información puedes leer"

---

Al final, en las notas, las números 4 , 5 y 16 inician con minúscula y debería ser mayúscula

No he conseguido ningún otro detalle de transcripción. Que libro tan interesante y que aporte tan grande que ustedes han realizado, mis felicitaciones y reconocimiento. Saludos

**Comment by yabellini** [comment]
Ernesto, ya he pasado todos estos cambios, pero no entiendo a que te refieres con "Al final, en las notas, las números 4 , 5 y 16 inician con minúscula y debería ser mayúscula", eso es en el capítulo de Marketing? Qué texto tiene alrrededor de esos números?

**Comment by ernestomirt** [comment]
Yanina, me refiero a las notas al pie de página (bueno, del texto completo) luego de las referencias bibliográficas. Dónde dice:

4. sigla de HyperText Markup Language en inglés↩︎

5. sigla de Cascading Style Sheets en inglés↩︎

y 

16. esta práctica se conoce como hardcodear↩︎

Entendería que esas notas deberían comenzar con mayúscula..!

**Comment by yabellini** [comment]
Excelente! Gracias por el detalle 🙌
