### ISSUE TITLE
Pedagogical content knowledge chapter

### ISSUE THREAD

**Issue by nmorandeira** [gvwilson/teachtogether.tech#465]
This is a suggestion for future editions:
Jargon on CS0, CS1 and CS2 seem specific to North America, are them? I'd try to use more generic terms, such as
Introductory course; Introductory semester-long course; Intermediate course;
and maybe the text can mention the name in ACM guidelines (and other popular guidelines, if available).

**Comment by yabellini** [comment]
En la sección 7.6 se dice: "nunca he visto un curso de pregrado dedicado a este tema", sigue siendo así?

**Comment by yabellini** [comment]
En la sección 7.1 se lista que se les está enseñando en los cursos formales. ¿Existirá alguna actualización?

**Comment by yabellini** [comment]
En el capítulo se vienen dando recomendaciones, amrcadas en itálicas y mencionadas como tal en cada sección.  La sección 7.7 no tiene esta recomendación.  ¿El último párrafo podría ser la recomendación?

**Comment by yabellini** [comment]
En la sección 7.8 agregar alguna mención a Hedy.

**Comment by yabellini** [comment]
En la sección 7.11 se pide que se publiquen los trabajos en Open Access y el uso de Sci-Hub para poder acceder a mucha de la investigación.  Más allá que estoy de acuerdo con publicaciones OA, en general son muy costosas para algunas partes del mundo, haciendo imposible poder publicar de esta manera.  Tal vez mencionar pre-prints o algo por el estilo.

Bib to support this point: https://t.co/F2dWRhe9UM

**Comment by yabellini** [comment]
Armar el mapa conceptual de este capítulo.  O al menos el resumen de "reglas":
- Para enseñar no basta con conocer sobre un tema. Hay que saber sobre lo que se quiere enseñar, Hay que saber sobre enseñanza y Hay que saber cómo enseñar ese tema en particular.
- Mide y haz un seguimiento de los resultados para poder comparar y ver si tus lecciones son efectivas.
- Enseña que la computadora es una "caja boba" y que no entiende a los programas.
- Primero leer código, luego modificar código, luego escribir código. 
- Presentar explicitamente patrones comunes y hacer que practiquen usandolos.
- Enseñar explicitamente como depurar errores.
- Enseñar a rastrear los valores que toman las variables al depurar errores.
- Enseñar como leer e interpretar mensajes de error.
- Enseña buenas practicas de programación desde el inicio (pero reflexiona si vos las usas también)
- El lenguaje importa: presentale interfaces basadas en bloques a infantes y adolecentes antes de avanzar a sistemas basdos en texto.
- Comenza enseñando funciones en vez de objetos (enseña casea despues que comprendan estructuras básicas de control y tipos de datos).
- Utiliza estilos y herramientas para garantizar que todos los ejemplos de código se adhieran a un estilo consistente.

**Comment by yabellini** [comment]
Trabajo sobre la imposibilidad del sur global de pagar publicaciones OA: https://direct.mit.edu/qss/article/2/4/1123/107612/Assessing-the-effect-of-article-processing-charges

7.11 si investigas, por favor ayuda a que ese día se acerque publicando tu trabajo en lugares de acceso abierto

Me gustaría agregar algo sobre el hecho que publicar con acceso abierto es prohibitivo para muchos/as (y debo confesar que no me causa ningún cargo de conciencia usar Sci-Hub) pero tal vez algo sobre pre-prints o algo similar.

**Comment by yabellini** [comment]
Bibligorafía sobre PCK para enseñar ciencias de la computación: https://dl.acm.org/doi/10.1145/3303770

**Comment by yabellini** [comment]
Moved to the repo of the second edition.
