### ISSUE TITLE
Add suggested citation for Spanish version

### ISSUE THREAD

**Issue by nmorandeira** [gvwilson/teachtogether.tech#469]
I would add a suggested citation for the Spanish version, maybe in this section https://teachtogether.tech/es/index.html#s:traduccion

This is my suggestion, to be discussed! 1st translation author @yabellini; 2nd author Natalia; follows alphabetical order

> Wilson, G. (2021). Enseñar tecnología en comunidad. Cómo crear y dar lecciones que funcionen y construir una comunidad docente a su alrededor [Teaching Tech Together. How to create and deliver lessons that work and build a teaching community around them]. Traducido al español por: Bellini Saibene, Y., N. S. Morandeira, L. Acion, M. Alonso, Z. Bazurto, A. Bellini, J. Benitez Saldivar, L. Canaviri Maydana, S. Canelón, R. Chirinos, P. Corrales, M. Dermit, A. L. Diedrich, P. Loto, P. Minotti, L. Rodríguez Planes, P. Rojas, Yuriko Sosa, N. Stroud, Y. Terrazas-Carafa, R. Noelía Villafañe. (Trabajo original publicado en 2019). Disponible en: https://teachtogether.tech/es/ 

Citation style is based on:
1) [This article in APA's blog](https://apastyle.apa.org/blog/citing-translated-works). Section _Book, republished in translation_ 
2) I've included the English title, following [this other  APA suggestion ](https://writeanswers.royalroads.ca/faq/199295). See example for Piaget (1950)

**Comment by nmorandeira** [comment]
No idea how to generate a bibtex for a translation @yabellini !

**Comment by yabellini** [comment]
I can order the rest of the translators by their contribution.  I have the record of what they translate and review. I can ask a librarian about how to generate a bibtex for the translation. Thanks for doing this Nati!

**Comment by nmorandeira** [comment]
Great! I agree with ordering the authors according to their contributions.

To remember for the 10sr: track the contributions :) you’ve done it on the ”repartija” sheet

**Comment by nmorandeira** [comment]
After discussing the author's order with @yabellini, we got this **suggested citation for the Spanish version**:

> Wilson, G. (2021). Enseñar tecnología en comunidad. Cómo crear y dar lecciones que funcionen y construir una comunidad docente a su alrededor [Teaching Tech Together. How to create and deliver lessons that work and build a teaching community around them] (Traducción al español: Y. Bellini Saibene, N. S. Morandeira, P. Corrales, L. Acion, M. Dermit, Y. Sosa, J. Benitez Saldivar, Z. Bazurto, S. Canelón, L. Canaviri Maydana, M. Alonso, A. Bellini, P. Minotti, R. Chirinos, P. Rojas, N. Stroud, R. N. Villafañe, P. Loto, A. L. Diedrich, Y. Terrazas-Carafa & L. Rodríguez Planes). https://teachtogether.tech/es/ (Trabajo original publicado en 2019)

**How did we get to his author's order?** (I continue in Spanish)
**Resumen del criterio de autorías**

Ordenamos las autorías considerando las contribuciones de cada una, que fueron registradas por Yanina durante el proceso de traducción. Los posibles tipos de contribución son: traducciones, primera revisión, segunda revisión, traducciones y revisiones de figuras, construcción de alt-text para las figuras, traducción de referencias bibliográficas, tareas de dirección, edición general y conceptualización general. Para ordenar las contribuciones de traducción y revisión de texto, construimos un índice que pondera la cantidad de palabras traducidas y revisadas por cada persona (traducción pesa 1; primera revisión pesa 0,6; segunda revisión pesa 0,4).

**Sobre el estilo de la cita**
Está basado en:
- [Este artículo en el blog de estilo APA](https://apastyle.apa.org/blog/citing-translated-works). Sección Book, republished in translation
- Incluimos además el título en inglés, de acuerdo a [esta otra sugerencia del estilo APA](https://writeanswers.royalroads.ca/faq/199295). Ver ejemplo para Piaget (1950)

**Pendientes**

- [ ] Agregar al readme
- [ ] Generar bibtex
- [ ] Agregar cita sugerida al libro online
- [ ] Comunicar a autoras y Greg -> Slack

**Comment by gvwilson** [comment]
:+1:

**Comment by yabellini** [comment]
Nunca recibí una contestación de la red de biblitoecarios sobre como generar el bibtex, pero ya la usamos en el readme y también está en el libro en el capítulo Sobre la traducción.  Lo mencionamos también en el artículo para DSbyD.
